CREATE TABLE device_template_categories (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE device_templates (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id INTEGER NOT NULL REFERENCES device_template_categories,
    device_type TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    make TEXT NOT NULL,
    model TEXT NOT NULL,
    protocol TEXT,
    address TEXT,
    port INTEGER,
    polling_interval INTEGER,
    settings ${jsonColumnType},
    UNIQUE (category_id, name)
);
