CREATE TABLE tracking.ad_hoc_observation_types (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE tracking.ad_hoc_plot_observations (
    boundary GEOMETRY(MultiPolygon) NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    elevation_meters INTEGER,
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE,
    observation_type INTEGER NOT NULL REFERENCES tracking.ad_hoc_observation_types,
    name TEXT,
    size_hectares NUMERIC NOT NULL
);

CREATE TABLE tracking.ad_hoc_plot_observation_photos (
    ad_hoc_plot_observation_id BIGINT NOT NULL REFERENCES tracking.ad_hoc_plot_observations,
    file_id BIGINT PRIMARY KEY REFERENCES files ON DELETE CASCADE,
    gps_coordinates GEOMETRY(Point),
    position_id INTEGER NOT NULL REFERENCES tracking.observation_plot_positions
);

CREATE INDEX ON tracking.ad_hoc_plot_observation_photos (ad_hoc_plot_observation_id);
CREATE INDEX ON tracking.ad_hoc_plot_observation_photos (file_id);
