DROP TABLE tracking.recorded_branches;
DROP TABLE tracking.recorded_trees;

CREATE TABLE tracking.recorded_trees (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    observation_id BIGINT NOT NULL REFERENCES tracking.observations ON DELETE CASCADE,
    monitoring_plot_id BIGINT NOT NULL REFERENCES tracking.monitoring_plots ON DELETE CASCADE,
    biomass_species_id BIGINT NOT NULL REFERENCES tracking.observation_biomass_species ON DELETE CASCADE,
    tree_number INTEGER NOT NULL CHECK ( tree_number >= 1 ),
    trunk_number INTEGER NOT NULL CHECK ( tree_number >= 1 ),
    tree_growth_form_id INTEGER NOT NULL REFERENCES tracking.tree_growth_forms,
    is_dead BOOLEAN NOT NULL,
    diameter_at_breast_height_cm INTEGER CHECK ( diameter_at_breast_height_cm >= 0 ),
    point_of_measurement_m NUMERIC CHECK ( point_of_measurement_m >= 0 ),
    height_m NUMERIC CHECK ( height_m >= 0 ),
    shrub_diameter_cm NUMERIC CHECK ( shrub_diameter_cm >= 0 ),
    description TEXT,

    CONSTRAINT growth_form_specific_data
    CHECK (
        (tree_growth_form_id = 1
             AND diameter_at_breast_height_cm IS NOT NULL
             AND point_of_measurement_m IS NOT NULL
             AND height_m IS NOT NULL
             AND shrub_diameter_cm IS NULL) OR
        (tree_growth_form_id = 2
             AND diameter_at_breast_height_cm IS NULL
             AND point_of_measurement_m IS NULL
             AND height_m IS NULL
             AND shrub_diameter_cm IS NOT NULL) OR
        (tree_growth_form_id = 3
             AND diameter_at_breast_height_cm IS NOT NULL
             AND point_of_measurement_m IS NOT NULL
             AND height_m IS NULL
             AND shrub_diameter_cm IS NULL)
     ),

    FOREIGN KEY (observation_id, monitoring_plot_id, biomass_species_id)
         REFERENCES tracking.observation_biomass_species (observation_id, monitoring_plot_id, id)
         ON DELETE CASCADE,

    UNIQUE (observation_id, tree_number, trunk_number)
);
