CREATE TABLE accelerator.metric_types(
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE accelerator.metric_components(
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE accelerator.standard_metrics(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type_id INTEGER NOT NULL REFERENCES accelerator.metric_types,
    component_id INTEGER NOT NULL REFERENCES accelerator.metric_components,
    name TEXT NOT NULL,
    description TEXT,
    reference TEXT NOT NULL
);

CREATE TABLE accelerator.report_standard_metrics(
    report_id BIGINT NOT NULL REFERENCES accelerator.reports ON DELETE CASCADE,
    standard_metric_id BIGINT NOT NULL REFERENCES accelerator.standard_metrics,
    target INTEGER,
    value INTEGER,
    notes TEXT,
    internal_comment TEXT,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,

    PRIMARY KEY (report_id, standard_metric_id)
);
