CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE docprod.variable_value_vectors (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    organization_id BIGINT NOT NULL REFERENCES organizations,
    project_id BIGINT REFERENCES projects,
    variable_id BIGINT NOT NULL REFERENCES docprod.variables,
    variable_value_id BIGINT NOT NULL REFERENCES docprod.variable_values,
    chunk_number INTEGER NOT NULL,
    text_value TEXT NOT NULL,
    embedding VECTOR(1536) NOT NULL
);
