CREATE TABLE accelerator.project_metrics(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_id BIGINT NOT NULL REFERENCES projects ON DELETE CASCADE,
    type_id INTEGER NOT NULL REFERENCES accelerator.metric_types,
    component_id INTEGER NOT NULL REFERENCES accelerator.metric_components,
    name TEXT NOT NULL,
    description TEXT,
    reference TEXT NOT NULL
);
CREATE INDEX ON accelerator.project_metrics(project_id);

CREATE TABLE accelerator.report_project_metrics(
    report_id BIGINT NOT NULL REFERENCES accelerator.reports ON DELETE CASCADE,
    project_metric_id BIGINT NOT NULL REFERENCES accelerator.project_metrics,
    target INTEGER,
    value INTEGER,
    notes TEXT,
    internal_comment TEXT,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,

    PRIMARY KEY (report_id, project_metric_id)
);
CREATE INDEX ON accelerator.report_project_metrics(project_metric_id);
CREATE INDEX ON accelerator.report_project_metrics(report_id, project_metric_id);

CREATE INDEX ON accelerator.report_standard_metrics(standard_metric_id);
CREATE INDEX ON accelerator.report_standard_metrics(report_id, standard_metric_id);
