CREATE TABLE accelerator.funding_entities
(
    id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE accelerator.funding_entity_projects
(
    funding_entity_id BIGINT NOT NULL REFERENCES accelerator.funding_entities,
    project_id        BIGINT NOT NULL REFERENCES projects
);
CREATE INDEX ON accelerator.funding_entity_projects(funding_entity_id);
CREATE INDEX ON accelerator.funding_entity_projects(project_id);


CREATE TABLE accelerator.funding_entity_users
(
    funding_entity_id BIGINT NOT NULL REFERENCES accelerator.funding_entities,
    user_id           BIGINT NOT NULL REFERENCES users
);
CREATE INDEX ON accelerator.funding_entity_users(funding_entity_id);
CREATE INDEX ON accelerator.funding_entity_users(user_id);
