CREATE SCHEMA IF NOT EXISTS funder;

CREATE TABLE funder.funding_entities
(
    id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE,
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE funder.funding_entity_projects
(
    funding_entity_id BIGINT NOT NULL REFERENCES funder.funding_entities ON DELETE CASCADE,
    project_id        BIGINT NOT NULL REFERENCES projects ON DELETE CASCADE
);
CREATE INDEX ON funder.funding_entity_projects(funding_entity_id);
CREATE INDEX ON funder.funding_entity_projects(project_id);


CREATE TABLE funder.funding_entity_users
(
    user_id           BIGINT PRIMARY KEY REFERENCES users ON DELETE CASCADE,
    funding_entity_id BIGINT NOT NULL REFERENCES funder.funding_entities ON DELETE CASCADE
);
CREATE INDEX ON funder.funding_entity_users(funding_entity_id);
CREATE INDEX ON funder.funding_entity_users(user_id);
