CREATE TABLE splat_annotations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    file_id BIGINT REFERENCES files,
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,
    title TEXT NOT NULL,
    text TEXT,
    label TEXT,
    position GEOMETRY(POINTZ, 0) NOT NULL,
    camera_position GEOMETRY(POINTZ, 0)
);
