CREATE TABLE splat_annotations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    file_id BIGINT REFERENCES files,
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,
    title TEXT NOT NULL,
    body_text TEXT,
    label TEXT,
    position_x NUMERIC NOT NULL,
    position_y NUMERIC NOT NULL,
    position_z NUMERIC NOT NULL,
    camera_position_x NUMERIC,
    camera_position_y NUMERIC,
    camera_position_z NUMERIC,
    CONSTRAINT camera_position_all_or_none CHECK (
        (camera_position_x IS NULL AND camera_position_y IS NULL AND camera_position_z IS NULL) OR
        (camera_position_x IS NOT NULL AND camera_position_y IS NOT NULL AND
         camera_position_z IS NOT NULL)
        )
);
