CREATE TABLE event_log (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_by BIGINT NOT NULL REFERENCES users (id),
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    event_class TEXT NOT NULL,
    payload JSONB NOT NULL,
    original_event_class TEXT,
    original_payload JSONB
);

CREATE INDEX ON event_log (created_by);
CREATE INDEX ON event_log (created_time);
CREATE INDEX ON event_log (event_class);

CREATE PROCEDURE event_log_create_id_index(field_name TEXT) AS $$
    DECLARE
        -- Field name surrounded by single quotes, e.g., 'fooId'
        quoted_field_name TEXT := '''' || field_name || '''';
    BEGIN
        EXECUTE 'CREATE INDEX event_log_' || LOWER(field_name) || '_idx' ||
                ' ON event_log (CAST(payload->>' || quoted_field_name || ' AS BIGINT), event_class)' ||
                ' WHERE payload->>' || quoted_field_name || ' IS NOT NULL;';
    END;
$$ LANGUAGE plpgsql;

CALL event_log_create_id_index('accessionId');
CALL event_log_create_id_index('activityId');
CALL event_log_create_id_index('batchId');
CALL event_log_create_id_index('facilityId');
CALL event_log_create_id_index('observationId');
CALL event_log_create_id_index('organizationId');
CALL event_log_create_id_index('projectId');
CALL event_log_create_id_index('plantingSiteId');
CALL event_log_create_id_index('withdrawalId');
