CREATE TABLE tracking.planting_season_statuses (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE tracking.planting_seasons (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    planting_site_id BIGINT NOT NULL REFERENCES tracking.planting_sites ON DELETE CASCADE,
    name TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status_id INTEGER NOT NULL REFERENCES tracking.planting_season_statuses,
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,

    CHECK (end_date >= start_date),
    UNIQUE (planting_site_id, name)
);

CREATE INDEX ON tracking.planting_seasons (planting_site_id);

CREATE TABLE tracking.planting_season_species_targets (
    planting_season_id BIGINT NOT NULL REFERENCES tracking.planting_seasons ON DELETE CASCADE,
    substratum_id BIGINT NOT NULL REFERENCES tracking.substrata ON DELETE CASCADE,
    species_id BIGINT NOT NULL REFERENCES species ON DELETE CASCADE,
    quantity INTEGER NOT NULL CHECK (quantity >= 0),
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,

    PRIMARY KEY (planting_season_id, substratum_id, species_id)
);

CREATE INDEX ON tracking.planting_season_species_targets (substratum_id);
CREATE INDEX ON tracking.planting_season_species_targets (species_id);

CREATE TABLE tracking.scheduled_planting_dates (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    planting_season_id BIGINT NOT NULL REFERENCES tracking.planting_seasons ON DELETE CASCADE,
    date DATE NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,

    UNIQUE (planting_season_id, date)
);

CREATE INDEX ON tracking.scheduled_planting_dates (planting_season_id);

CREATE TABLE tracking.scheduled_planting_date_species (
    scheduled_planting_date_id BIGINT NOT NULL REFERENCES tracking.scheduled_planting_dates ON DELETE CASCADE,
    substratum_id BIGINT NOT NULL REFERENCES tracking.substrata ON DELETE CASCADE,
    species_id BIGINT NOT NULL REFERENCES species ON DELETE CASCADE,
    quantity INTEGER NOT NULL CHECK (quantity >= 0),

    PRIMARY KEY (scheduled_planting_date_id, substratum_id, species_id)
);

CREATE INDEX ON tracking.scheduled_planting_date_species (substratum_id);
CREATE INDEX ON tracking.scheduled_planting_date_species (species_id);
