phrase:
  project_id: "14fb7d64f7ca5bfa104cc84436aa836c"
  file_format: properties

  push:
    sources:
      - file: src/main/resources/i18n/Messages.properties
        params:
          file_encoding: UTF-8
          format_properties:
            escape_single_quotes: true
          tags: messages

  pull:
    targets:
      - file: src/main/resources/i18n/Messages_es.properties
        params:
          file_encoding: UTF-8
          format_properties:
            escape_single_quotes: true
            omit_separator_space: true
          locale_id: "969d0e901a1bb5aa7dcb24103a59ead8"
          tags: messages
