openapi: 3.0.1
info:
  title: Terraware Seed Bank
  description: Local server API for seed banks
  license:
    name: MIT
  version: 0.1-SNAPSHOT
servers:
- url: http://localhost:32109
  description: Generated server url
paths:
  /api/v1/seedbank/summary/updates:
    get:
      tags:
      - SeedBankApp
      summary: Get accession state update summary
      description: A summary of the number of accessions in each of several states.
      operationId: getStateUpdates
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/StateUpdateSummaryResponse'
  /api/v1/seedbank/summary/species:
    get:
      tags:
      - SeedBankApp
      summary: Get species summary
      description: A summary of species including a list of the species with the most
        accessions.
      operationId: getSpecies
      parameters:
      - name: maxCount
        in: query
        description: The maximum number of per-species counts to include.
        required: false
        schema:
          maximum: 100
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SpeciesSummaryResponse'
  /api/v1/seedbank/summary/accessions:
    get:
      tags:
      - SeedBankApp
      summary: Get accessions summary
      description: A summary of active accessions broken down by state.
      operationId: getAccessions
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AccessionSummaryResponse'
components:
  schemas:
    StateUpdateSummaryResponse:
      required:
      - dried
      - droppedOff
      - processed
      - withdrawn
      type: object
      properties:
        droppedOff:
          type: integer
          description: Number of accessions currently waiting to be labeled and processed.
          format: int32
        processed:
          type: integer
          description: Number of accessions that have been processed and are ready
            to be dried. This does not include accessions that have been processed
            but are not yet ready to be dried.
          format: int32
        dried:
          type: integer
          description: Number of accessions that have been dried and are ready to
            be stored. This does not include accessions that have been dried but are
            not yet ready to be stored.
          format: int32
        withdrawn:
          type: integer
          description: Number of accessions that have been completely withdrawn recently.
          format: int32
    SpeciesSummaryResponse:
      required:
      - accessionsPerSpecies
      - lastWeekTotal
      - total
      type: object
      properties:
        total:
          type: integer
          description: Total number of distinct seed species in the seed bank.
          format: int32
        lastWeekTotal:
          type: integer
          description: How many species were in the seed bank last week.
          format: int32
        accessionsPerSpecies:
          type: object
          additionalProperties:
            type: integer
            description: Number of accessions for each of the most numerous species.
            format: int32
          description: Number of accessions for each of the most numerous species.
      description: Summary of the number of species whose seeds are currently present
        in the seed bank.
    AccessionSummaryResponse:
      required:
      - drying
      - lastWeekTotal
      - processing
      - storage
      - testing
      - total
      type: object
      properties:
        total:
          type: integer
          description: Total number of active accessions.
          format: int32
        lastWeekTotal:
          type: integer
          description: Number of active accessions as of last week.
          format: int32
        processing:
          type: integer
          format: int32
        drying:
          type: integer
          format: int32
        storage:
          type: integer
          format: int32
        testing:
          type: integer
          format: int32
      description: Summary of active accessions including the number currently in
        each state.
  securitySchemes:
    ApiKey:
      type: http
      description: Key-based authentication for non-browser-based clients. Username
        is currently ignored; password should be the API key.
      scheme: basic
