openapi: 3.0.1
info:
  title: Terraware Seed Bank
  description: Local server API for seed banks
  license:
    name: MIT
  version: 0.1-SNAPSHOT
servers:
- url: http://localhost:32109
  description: Generated server url
paths:
  /api/v1/seedbank/notification/{id}/markRead:
    post:
      tags:
      - SeedBankApp
      summary: Mark a specific notification as read.
      operationId: markRead
      parameters:
      - name: id
        in: path
        description: ID of notification to mark as read
        required: true
        schema:
          type: string
      responses:
        "404":
          description: The requested notification ID was not valid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleErrorResponsePayload'
        "200":
          description: Notification has been marked as read.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleSuccessResponsePayload'
  /api/v1/seedbank/notification/all/markRead:
    post:
      tags:
      - SeedBankApp
      summary: Mark all unread notifications as read.
      operationId: markAllRead
      responses:
        "200":
          description: All notifications have been marked as read.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleSuccessResponsePayload'
        "404":
          description: The requested resource was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleErrorResponsePayload'
  /api/v1/seedbank/summary:
    get:
      tags:
      - SeedBankApp
      summary: Get summary statistics about the seed bank
      operationId: getSummary
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SummaryResponse'
  /api/v1/seedbank/notification:
    get:
      tags:
      - SeedBankApp
      summary: Get a list of recent notifications
      operationId: listAll
      parameters:
      - name: since
        in: query
        description: Don't return notifications older than this; default is 1 month
          ago
        required: false
        schema:
          type: string
          format: date-time
      - name: limit
        in: query
        description: Return at most this many notifications; default is no limit
        required: false
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: Notifications in reverse time order (newest first).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationListResponse'
components:
  schemas:
    ErrorDetails:
      required:
      - message
      type: object
      properties:
        message:
          type: string
    SimpleErrorResponsePayload:
      required:
      - error
      - status
      type: object
      properties:
        error:
          $ref: '#/components/schemas/ErrorDetails'
        status:
          $ref: '#/components/schemas/SuccessOrError'
    SuccessOrError:
      type: string
      description: Indicates of success or failure of the requested operation.
      enum:
      - ok
      - error
    SimpleSuccessResponsePayload:
      required:
      - status
      type: object
      properties:
        status:
          $ref: '#/components/schemas/SuccessOrError'
    SummaryResponse:
      required:
      - activeAccessions
      - families
      - overdueDriedAccessions
      - overduePendingAccessions
      - overdueProcessedAccessions
      - recentlyWithdrawnAccessions
      - species
      type: object
      properties:
        activeAccessions:
          $ref: '#/components/schemas/SummaryStatistic'
        species:
          $ref: '#/components/schemas/SummaryStatistic'
        families:
          $ref: '#/components/schemas/SummaryStatistic'
        overduePendingAccessions:
          type: integer
          description: Number of accessions in Pending state overdue for processing
          format: int32
        overdueProcessedAccessions:
          type: integer
          description: Number of accessions in Processed state overdue for drying
          format: int32
        overdueDriedAccessions:
          type: integer
          description: Number of accessions in Dried state overdue for storage
          format: int32
        recentlyWithdrawnAccessions:
          type: integer
          description: Number of accessions withdrawn so far this week
          format: int32
      description: Summary of important statistics about the seed bank for the Summary
        page.
    SummaryStatistic:
      required:
      - current
      - lastWeek
      type: object
      properties:
        current:
          type: integer
          format: int32
        lastWeek:
          type: integer
          format: int32
      description: The current value and value as of last week for a summary statistic
    NotificationListResponse:
      required:
      - notifications
      - status
      type: object
      properties:
        notifications:
          type: array
          items:
            $ref: '#/components/schemas/NotificationPayload'
        status:
          $ref: '#/components/schemas/SuccessOrError'
    NotificationPayload:
      required:
      - id
      - read
      - text
      - timestamp
      - type
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for this notification. Clients should treat
            it as opaque.
          example: "12345"
        timestamp:
          type: string
          format: date-time
        type:
          type: string
          enum:
          - Alert
          - State
          - Date
        read:
          type: boolean
          description: "If true, this notification has been marked as read."
        text:
          type: string
          description: Plain-text body of notification.
          example: Accession XYZ is ready to be dried.
  securitySchemes:
    ApiKey:
      type: http
      description: Key-based authentication for non-browser-based clients. Username
        is currently ignored; password should be the API key.
      scheme: basic
