CREATE TABLE accelerator.system_metrics(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    type_id INTEGER NOT NULL REFERENCES accelerator.metric_types,
    component_id INTEGER NOT NULL REFERENCES accelerator.metric_components,
    description TEXT,
    reference TEXT COLLATE natural_numeric NOT NULL
);

CREATE TABLE accelerator.report_system_metrics(
    report_id BIGINT NOT NULL REFERENCES accelerator.reports ON DELETE CASCADE,
    system_metric_id INTEGER NOT NULL REFERENCES accelerator.system_metrics,
    target INTEGER,
    system_value INTEGER,
    system_time TIMESTAMP WITH TIME ZONE,
    override_value INTEGER,
    notes TEXT,
    internal_comment TEXT,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,

    PRIMARY KEY (report_id, system_metric_id)
);

CREATE INDEX ON accelerator.report_system_metrics(system_metric_id);
CREATE INDEX ON accelerator.report_system_metrics(report_id, system_metric_id);
