CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE vector_store (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    content TEXT,
    metadata JSONB,
    embedding vector(1536)
);

CREATE INDEX ON vector_store USING HNSW (embedding vector_cosine_ops);

CREATE INDEX ON vector_store ((metadata ->> 'projectId'));

CREATE TABLE chat_memory_conversations (
    id uuid PRIMARY KEY,
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE chat_memory_message_types (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE chat_memory_messages (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    conversation_id uuid NOT NULL REFERENCES chat_memory_conversations (id) ON DELETE CASCADE,
    message_type_id INTEGER NOT NULL REFERENCES chat_memory_message_types,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    content TEXT NOT NULL
);

CREATE INDEX ON chat_memory_messages (conversation_id);
