CREATE PROCEDURE add_survival_rate_column(table_name TEXT) AS $$
    BEGIN
        EXECUTE 'ALTER TABLE tracking.' || table_name || '
                ADD COLUMN survival_rate INTEGER';
    END;
$$ LANGUAGE plpgsql;

CALL add_survival_rate_column('observed_plot_species_totals');
CALL add_survival_rate_column('observed_subzone_species_totals');
CALL add_survival_rate_column('observed_zone_species_totals');
CALL add_survival_rate_column('observed_site_species_totals');

DROP PROCEDURE add_survival_rate_column;

CREATE TABLE tracking.t0_plot
(
    id                         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    monitoring_plot_id         BIGINT NOT NULL REFERENCES tracking.monitoring_plots ON DELETE CASCADE,
    observation_id             BIGINT REFERENCES tracking.observations ON DELETE CASCADE,
    species_id                 BIGINT REFERENCES species ON DELETE CASCADE,
    estimated_planting_density NUMERIC,

    CONSTRAINT t0_plot_null_check CHECK (
        (observation_id IS NULL AND estimated_planting_density IS NOT NULL AND
         species_id IS NOT NULL) OR
        (observation_id IS NOT NULL AND estimated_planting_density IS NULL AND species_id IS NULL)
    ),

    CONSTRAINT unique_plot_observation UNIQUE (monitoring_plot_id, observation_id),

    CONSTRAINT unique_plot_species UNIQUE (monitoring_plot_id, species_id)

);
