ALTER TABLE tracking.observed_plot_species_totals    ADD COLUMN survival_rate INTEGER;
ALTER TABLE tracking.observed_subzone_species_totals ADD COLUMN survival_rate INTEGER;
ALTER TABLE tracking.observed_zone_species_totals    ADD COLUMN survival_rate INTEGER;
ALTER TABLE tracking.observed_site_species_totals    ADD COLUMN survival_rate INTEGER;

CREATE TABLE tracking.t0_plot
(
    id                         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    monitoring_plot_id         BIGINT NOT NULL REFERENCES tracking.monitoring_plots ON DELETE CASCADE,
    observation_id             BIGINT REFERENCES tracking.observations ON DELETE CASCADE,
    species_id                 BIGINT REFERENCES species ON DELETE CASCADE,
    estimated_planting_density NUMERIC,

    CONSTRAINT t0_plot_null_check CHECK (
        (observation_id IS NULL AND estimated_planting_density IS NOT NULL AND
         species_id IS NOT NULL) OR
        (observation_id IS NOT NULL AND estimated_planting_density IS NULL AND species_id IS NULL)
    ),

    CONSTRAINT unique_plot_species UNIQUE (monitoring_plot_id, species_id)
);

CREATE UNIQUE INDEX ON tracking.t0_plot (monitoring_plot_id)
WHERE observation_id IS NOT NULL;

CREATE INDEX ON tracking.t0_plot (monitoring_plot_id);
CREATE INDEX ON tracking.t0_plot (observation_id);
CREATE INDEX ON tracking.t0_plot (species_id);
