# Configuration overrides for instances of the server running on site as part of a Balena
# multi-service deployment.

terraware:
  photo-dir: "/data/photos"

logging:
  level:
    root: WARN
    com.terraformation: DEBUG
