# Configuration overrides for instances of the server running on site as part of a Balena
# multi-service deployment.

logging:
  level:
    com.terraformation: INFO

terraware:
  jwt-secret: "${TERRAWARE_JWT_SECRET:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=}"
  mqtt:
    enabled: true
    address: "ws://mosquitto:1883/"
