# Application profile for build-time API documentation (openapi.yaml) generation. Since dumping
# out the API docs only requires scanning the annotations and method declarations of various
# application classes, not actually running any application code, the idea here is to strip out
# all the initialization and minimize runtime dependencies so the build step is fast and reliable.
#
# Note that the base application.yaml is also used (this file overrides it). Many of the OpenAPI
# settings are there instead of here so that they also apply to the API docs endpoints when the
# server is running.

spring:
  flyway:
    # Don't do database migrations since we don't want to talk to a database at all.
    enabled: false
  main:
    # Don't instantiate any beans that aren't actually used in the course of processing the request
    # to dump out the API docs.
    lazy-initialization: true
    # Don't show the "Spring" logo.
    banner-mode: "off"
  jooq:
    sql-dialect: default
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: "client-credentials"
            client-id: "dummy"
        provider:
          keycloak:
            jwk-set-uri: "dummy"
            token-uri: "dummy"
            authorization-uri: "dummy"
            user-info-uri: "dummy"
      resourceserver:
        jwt:
          issuer-uri: "dummy"
  session:
    store-type: none

terraware:
  web-app-url: http://dummy
  photo-dir: "/tmp"
  daily-tasks:
    enabled: false
  keycloak:
    apiClientId: dummy

org:
  jobrunr:
    background-job-server:
      enabled: false
    job-scheduler:
      enabled: false
    database:
      skip-create: true

logging:
  level:
    root: warn
