# Configuration overrides for the "dev" environment. This mostly sets default values for config
# options that we want to make sure are set explicitly in production environments.

flyway:
  datasources:
    default:
      enabled: true
      locations:
        # Allow dev-specific migrations, e.g., to insert dummy test data
        - "classpath:db/migration/dev"
        - "classpath:db/migration/postgres"
        - "classpath:db/migration/common"

micronaut:
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${TERRAWARE_JWT_SECRET:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=}"

terraware:
  jwt-secret: "${TERRAWARE_JWT_SECRET:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=}"
  organization-id: 1
  seedbank-id: 1
