# Configuration overrides for instances of the server running on site as part of a Balena
# multi-service deployment.


logging:
  level:
    com.terraformation: DEBUG

terraware:
  jwt-secret: "${TERRAWARE_JWT_SECRET:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=}"
  mqtt:
    enabled: true
    address: "ws://mosquitto:1883/"

server:
  tomcat:
    accesslog:
      enabled: true
      directory: "/dev"
      prefix: "stdout"
      suffix: ""
      file-date-format: ""
      buffered: false
