CREATE TABLE automations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    facility_id BIGINT NOT NULL REFERENCES facilities,
    name TEXT NOT NULL,
    description TEXT,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,
    configuration ${jsonColumnType}
);

CREATE INDEX ON automations (facility_id, name);
