CREATE TABLE notification_criticalities (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE notification_types (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  notification_criticality_id INTEGER NOT NULL REFERENCES notification_criticalities
);

CREATE TABLE notifications (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    notification_type_id INTEGER NOT NULL REFERENCES notification_types,
    user_id BIGINT NOT NULL REFERENCES users,
    organization_id BIGINT REFERENCES organizations,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    local_url TEXT NOT NULL,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE
);
