# See .buildkite/README.md for details about this pipeline.

common:
  - &cache-common-args
    backend: s3
    compression: tgz
    restore: pipeline

  - _: &cache-gradle-home-manifest
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"

  - &cache-gradle-home-args
    <<: *cache-common-args
    path: ".gradle-home"
    manifest: *cache-gradle-home-manifest

  - _: &cache-node-modules-manifest
      - "yarn.lock"

  - &cache-node-modules-args
    <<: *cache-common-args
    path: "node_modules"
    manifest: *cache-node-modules-manifest

  - &cache-pip-args
    <<: *cache-common-args
    path: "scripts/.pip-cache"
    manifest:
      - "scripts/requirements.txt"
      - ".buildkite/scripts/check-scripts.sh"

  - _: &cache-buildx-manifest
      - "docker/Dockerfile"
      - "docker/Makefile"
      - "docker/start.sh"
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"

  - &load-secrets
    seek-oss/aws-sm#v2.4.1:
      json-to-env:
        - secret-id: "buildkite_build_secrets"
        - secret-id: "terraware_server_build_secrets"

  - &shallow-clone
    peakon/git-shallow-clone#v0.0.1:
      depth: 1

  - &use-existing-checkout
    checkout:
      skip: true
    retry:
      manual:
        allowed: false


agents:
  # Run all steps on the same kind of runner.
  queue: "x86-8core"

env:
  BUILDKITE_ARTIFACT_UPLOAD_DESTINATION: "s3://$BUILDKITE_PLUGIN_S3_CACHE_BUCKET/artifacts/$BUILDKITE_PIPELINE_SLUG/$BUILDKITE_BUILD_ID"

steps:
  - label: ":graphite: CI optimizer"
    key: "graphite-ci-optimizer"
    soft_fail: true
    plugins:
      - *shallow-clone
      - *load-secrets
    command: .buildkite/scripts/graphite-optimizer.sh

  - wait: ~
    continue_on_failure: true

  - <<: *use-existing-checkout
    label: ":gradle: Compile"
    key: "build"
    plugins:
      - cache#v1.12.0:
          <<: *cache-gradle-home-args
          save:
            - file
      - cache#v1.12.0:
          <<: *cache-node-modules-args
          save:
            - file
    command: ".buildkite/scripts/build.sh"

  - <<: *use-existing-checkout
    label: ":gradle: Run tests"
    key: "run-tests"
    depends_on: "build"
    plugins:
      - artifacts#v1.9.4:
          # We need to upload the test results as individual files so they can be consumed by the
          # junit-annotate plugin.
          upload: "build/test-results/**/*.xml"
          s3-upload-acl: "private"
    command: ".buildkite/scripts/test.sh"

  - <<: *use-existing-checkout
    label: ":junit: Run external service integration tests"
    key: "external-tests"
    depends_on: "run-tests"
    soft_fail: true
    if: "build.branch != 'main' && build.tag == null"
    plugins:
      - *load-secrets
      - artifacts#v1.9.4:
          # We need to upload the test results as individual files so they can be consumed by the
          # junit-annotate plugin.
          upload: "build/test-results/**/*.xml"
          s3-upload-acl: "private"
    command: .buildkite/scripts/run-external-tests.sh
    env:
      TEST_S3_BUCKET_NAME: "terraformation-buildkite-test"

  - <<: *use-existing-checkout
    label: ":python: Check scripts"
    key: "check-scripts"
    depends_on:
      - step: "run-tests"
      - step: "external-tests"
        allow_failure: true
    if_changed: "scripts/**"
    plugins:
      - cache#v1.12.0:
          <<: *cache-pip-args
          save:
            - "file"
    command: .buildkite/scripts/check-scripts.sh

  - <<: *use-existing-checkout
    label: ":junit: Annotate build with test results"
    key: "junit-annotate"
    depends_on:
      - step: "run-tests"
      - step: "check-scripts"
      - step: "external-tests"
        allow_failure: true
    plugins:
      - junit-annotate#v2.7.0:
          artifacts: "build/test-results/**/*.xml"
          always-annotate: true
          report-slowest: 10

  - <<: *use-existing-checkout
    label: ":docker: Build and push Docker image"
    key: "docker"
    depends_on: "junit-annotate"
    plugins:
      - *load-secrets
      - cache#v1.12.0:
          <<: *cache-common-args
          path: ".buildx-cache"
          manifest: *cache-buildx-manifest
          save:
            - file
    command: .buildkite/scripts/docker-build-push.sh

  - <<: *use-existing-checkout
    label: ":buildkite: Promote Gradle home cache to pipeline-level"
    key: "promote-gradle-cache"
    depends_on: "docker"
    branches: "main"
    if_changed: *cache-gradle-home-manifest
    plugins:
      - cache#v1.12.0:
          <<: *cache-gradle-home-args
          save: "pipeline"
          force: true
    command: "rm -rf .gradle-home/caches/build-cache-1"

  - <<: *use-existing-checkout
    label: ":buildkite: Promote Node modules cache to pipeline-level"
    key: "promote-node-cache"
    depends_on:
      - "docker"
      - "promote-gradle-cache"
    branches: "main"
    if_changed: *cache-node-modules-manifest
    plugins:
      - cache#v1.12.0:
          <<: *cache-node-modules-args
          save: "pipeline"
          force: true
    command: "true"

  - <<: *use-existing-checkout
    label: ":buildkite: Promote branch-level script cache to pipeline-level"
    key: "promote-script-cache"
    depends_on:
      - "docker"
      - "promote-gradle-cache"
      - "promote-node-cache"
    branches: "main"
    if_changed: "scripts/**"
    plugins:
      - cache#v1.12.0:
          <<: *cache-pip-args
          save: "pipeline"
          force: true
    command: "true"

  - <<: *use-existing-checkout
    label: ":buildkite: Promote Docker build cache to pipeline-level"
    key: "promote-buildx-cache"
    depends_on:
      - "docker"
      - "promote-gradle-cache"
      - "promote-node-cache"
      - "promote-script-cache"
    branches: "main"
    if_changed: *cache-buildx-manifest
    plugins:
      - cache#v1.12.0:
          <<: *cache-common-args
          manifest: *cache-buildx-manifest
          path: ".buildx-cache"
          save: "pipeline"
          force: true
    command: "true"

  - <<: *use-existing-checkout
    label: ":amazon-ecs: Deploy to ECS"
    key: "deploy"
    concurrency: 1
    concurrency_group: "terraware-server/deploy"
    depends_on:
      - "docker"
      - "promote-buildx-cache"
      - "promote-gradle-cache"
      - "promote-node-cache"
      - "promote-script-cache"
    if: "build.branch == 'main' || build.tag =~ /^v2[0-9]+\\.[0-9]+/"
    plugins:
      - *load-secrets
    command: .buildkite/scripts/deploy-ecs.sh

  - <<: *use-existing-checkout
    label: ":slack: Release notes & Jira transitions"
    key: "release-notes"
    depends_on: "deploy"
    if: "build.tag =~ /^v2[0-9]+\\.[0-9]+/"
    plugins:
      - *load-secrets
    command: .buildkite/scripts/release-notes.sh

  - <<: *use-existing-checkout
    label: ":speech_balloon: Notify PR of staging deploy"
    key: "notify-pr"
    depends_on:
      - "deploy"
      - "release-notes"
    branches: "main"
    plugins:
      - *load-secrets
    command: .buildkite/scripts/notify-pr.sh

  - <<: *use-existing-checkout
    label: ":books: Generate and deploy unreleased commits log"
    key: "generate-unreleased"
    depends_on:
      - "notify-pr"
    branches:
      - "main"
    plugins:
      - *load-secrets
    command: .buildkite/scripts/deploy-main-docs.sh

  - <<: *use-existing-checkout
    label: ":books: Generate and deploy docs"
    key: "generate-docs"
    depends_on:
      - "deploy"
      - "generate-unreleased"
      - "release-notes"
    if: "build.tag =~ /^v2[0-9]+\\.[0-9]+/"
    plugins:
      - *load-secrets
    command: .buildkite/scripts/deploy-release-docs.sh

notify:
  - slack:
      channels:
        - "#buildkite-builds"
    if: build.state == "failed" && build.branch == "main"
