-- project_metric_id columns
ALTER TABLE accelerator.report_project_metrics RENAME COLUMN project_metric_id TO project_indicator_id;
ALTER TABLE funder.published_report_project_metrics RENAME COLUMN project_metric_id TO project_indicator_id;
ALTER TABLE accelerator.report_project_metric_targets RENAME COLUMN project_metric_id TO project_indicator_id;
ALTER TABLE funder.published_project_metric_targets RENAME COLUMN project_metric_id TO project_indicator_id;

-- tables
ALTER TABLE accelerator.project_metrics RENAME TO project_indicators;
ALTER TABLE accelerator.report_project_metrics RENAME TO report_project_indicators;
ALTER TABLE funder.published_report_project_metrics RENAME TO published_report_project_indicators;
ALTER TABLE accelerator.report_project_metric_targets RENAME TO report_project_indicator_targets;
ALTER TABLE funder.published_project_metric_targets RENAME TO published_project_indicator_targets;

ALTER SEQUENCE accelerator.project_metrics_id_seq RENAME TO project_indicators_id_seq;

-- constraints
ALTER TABLE accelerator.project_indicators RENAME CONSTRAINT project_metrics_pkey TO project_indicators_pkey;
ALTER TABLE accelerator.project_indicators RENAME CONSTRAINT project_metrics_project_id_fkey TO project_indicators_project_id_fkey;
ALTER TABLE accelerator.project_indicators RENAME CONSTRAINT project_metrics_type_id_fkey TO project_indicators_type_id_fkey;
ALTER TABLE accelerator.project_indicators RENAME CONSTRAINT project_metrics_component_id_fkey TO project_indicators_component_id_fkey;

ALTER TABLE accelerator.report_project_indicators RENAME CONSTRAINT report_project_metrics_pkey TO report_project_indicators_pkey;
ALTER TABLE accelerator.report_project_indicators RENAME CONSTRAINT report_project_metrics_report_id_fkey TO report_project_indicators_report_id_fkey;
ALTER TABLE accelerator.report_project_indicators RENAME CONSTRAINT report_project_metrics_project_metric_id_fkey TO report_project_indicators_project_indicator_id_fkey;
ALTER TABLE accelerator.report_project_indicators RENAME CONSTRAINT report_project_metrics_modified_by_fkey TO report_project_indicators_modified_by_fkey;
ALTER TABLE accelerator.report_project_indicators RENAME CONSTRAINT report_project_metrics_status_id_fkey TO report_project_indicators_status_id_fkey;

ALTER TABLE funder.published_report_project_indicators RENAME CONSTRAINT published_report_project_metrics_pkey TO published_report_project_indicators_pkey;
ALTER TABLE funder.published_report_project_indicators RENAME CONSTRAINT published_report_project_metrics_report_id_fkey TO published_report_project_indicators_report_id_fkey;
ALTER TABLE funder.published_report_project_indicators RENAME CONSTRAINT published_report_project_metrics_project_metric_id_fkey TO published_report_project_indicators_project_indicator_id_fkey;
ALTER TABLE funder.published_report_project_indicators RENAME CONSTRAINT published_report_project_metrics_status_id_fkey TO published_report_project_indicators_status_id_fkey;

ALTER TABLE accelerator.report_project_indicator_targets RENAME CONSTRAINT report_project_metric_targets_pkey TO report_project_indicator_targets_pkey;
ALTER TABLE accelerator.report_project_indicator_targets RENAME CONSTRAINT report_project_metric_targets_project_id_fkey TO report_project_indicator_targets_project_id_fkey;
ALTER TABLE accelerator.report_project_indicator_targets RENAME CONSTRAINT report_project_metric_targets_project_metric_id_fkey TO report_project_indicator_targets_project_indicator_id_fkey;

ALTER TABLE funder.published_project_indicator_targets RENAME CONSTRAINT published_project_metric_targets_pkey TO published_project_indicator_targets_pkey;
ALTER TABLE funder.published_project_indicator_targets RENAME CONSTRAINT published_project_metric_targets_project_id_fkey TO published_project_indicator_targets_project_id_fkey;
ALTER TABLE funder.published_project_indicator_targets RENAME CONSTRAINT published_project_metric_targets_project_metric_id_fkey TO published_project_indicator_targets_project_indicator_id_fkey;

-- indexes
ALTER INDEX accelerator.project_metrics_project_id_idx RENAME TO project_indicators_project_id_idx;
ALTER INDEX accelerator.report_project_metrics_project_metric_id_idx RENAME TO report_project_indicators_project_indicator_id_idx;
ALTER INDEX accelerator.report_project_metrics_report_id_project_metric_id_idx RENAME TO report_project_indicators_report_id_project_indicator_id_idx;
ALTER INDEX accelerator.report_project_metric_targets_project_id_year_idx RENAME TO report_project_indicator_targets_project_id_year_idx;
ALTER INDEX funder.published_project_metric_targets_project_id_year_idx RENAME TO published_project_indicator_targets_project_id_year_idx;
