-- standard_metric_id columns
ALTER TABLE accelerator.report_standard_metrics RENAME COLUMN standard_metric_id TO standard_indicator_id;
ALTER TABLE funder.published_report_standard_metrics RENAME COLUMN standard_metric_id TO standard_indicator_id;
ALTER TABLE accelerator.report_standard_metric_targets RENAME COLUMN standard_metric_id TO standard_indicator_id;
ALTER TABLE funder.published_standard_metric_targets RENAME COLUMN standard_metric_id TO standard_indicator_id;

-- tables
ALTER TABLE accelerator.standard_metrics RENAME TO standard_indicators;
ALTER TABLE accelerator.report_standard_metrics RENAME TO report_standard_indicators;
ALTER TABLE funder.published_report_standard_metrics RENAME TO published_report_standard_indicators;
ALTER TABLE accelerator.report_standard_metric_targets RENAME TO report_standard_indicator_targets;
ALTER TABLE funder.published_standard_metric_targets RENAME TO published_standard_indicator_targets;

ALTER SEQUENCE accelerator.standard_metrics_id_seq RENAME TO standard_indicators_id_seq;

-- constraints
ALTER TABLE accelerator.standard_indicators RENAME CONSTRAINT standard_metrics_pkey TO standard_indicators_pkey;
ALTER TABLE accelerator.standard_indicators RENAME CONSTRAINT standard_metrics_type_id_fkey TO standard_indicators_type_id_fkey;
ALTER TABLE accelerator.standard_indicators RENAME CONSTRAINT standard_metrics_component_id_fkey TO standard_indicators_component_id_fkey;

ALTER TABLE accelerator.report_standard_indicators RENAME CONSTRAINT report_standard_metrics_pkey TO report_standard_indicators_pkey;
ALTER TABLE accelerator.report_standard_indicators RENAME CONSTRAINT report_standard_metrics_report_id_fkey TO report_standard_indicators_report_id_fkey;
ALTER TABLE accelerator.report_standard_indicators RENAME CONSTRAINT report_standard_metrics_standard_metric_id_fkey TO report_standard_indicators_standard_indicator_id_fkey;
ALTER TABLE accelerator.report_standard_indicators RENAME CONSTRAINT report_standard_metrics_modified_by_fkey TO report_standard_indicators_modified_by_fkey;
ALTER TABLE accelerator.report_standard_indicators RENAME CONSTRAINT report_standard_metrics_status_id_fkey TO report_standard_indicators_status_id_fkey;

ALTER TABLE funder.published_report_standard_indicators RENAME CONSTRAINT published_report_standard_metrics_pkey TO published_report_standard_indicators_pkey;
ALTER TABLE funder.published_report_standard_indicators RENAME CONSTRAINT published_report_standard_metrics_report_id_fkey TO published_report_standard_indicators_report_id_fkey;
ALTER TABLE funder.published_report_standard_indicators RENAME CONSTRAINT published_report_standard_metrics_standard_metric_id_fkey TO published_report_standard_indicators_standard_indicator_id_fkey;
ALTER TABLE funder.published_report_standard_indicators RENAME CONSTRAINT published_report_standard_metrics_status_id_fkey TO published_report_standard_indicators_status_id_fkey;

ALTER TABLE accelerator.report_standard_indicator_targets RENAME CONSTRAINT report_standard_metric_targets_pkey TO report_standard_indicator_targets_pkey;
ALTER TABLE accelerator.report_standard_indicator_targets RENAME CONSTRAINT report_standard_metric_targets_project_id_fkey TO report_standard_indicator_targets_project_id_fkey;
ALTER TABLE accelerator.report_standard_indicator_targets RENAME CONSTRAINT report_standard_metric_targets_standard_metric_id_fkey TO report_standard_indicator_targets_standard_indicator_id_fkey;

ALTER TABLE funder.published_standard_indicator_targets RENAME CONSTRAINT published_standard_metric_targets_pkey TO published_standard_indicator_targets_pkey;
ALTER TABLE funder.published_standard_indicator_targets RENAME CONSTRAINT published_standard_metric_targets_project_id_fkey TO published_standard_indicator_targets_project_id_fkey;
ALTER TABLE funder.published_standard_indicator_targets RENAME CONSTRAINT published_standard_metric_targets_standard_metric_id_fkey TO published_standard_indicator_targets_standard_indicator_id_fkey;

-- indexes
ALTER INDEX accelerator.report_standard_metric_targets_project_id_year_idx RENAME TO report_standard_indicator_targets_project_id_year_idx;
ALTER INDEX funder.published_standard_metric_targets_project_id_year_idx RENAME TO published_standard_indicator_targets_project_id_year_idx;
