-- system_metric_id columns
ALTER TABLE accelerator.report_system_metrics RENAME COLUMN system_metric_id TO auto_calculated_indicator_id;
ALTER TABLE funder.published_report_system_metrics RENAME COLUMN system_metric_id TO auto_calculated_indicator_id;
ALTER TABLE accelerator.report_system_metric_targets RENAME COLUMN system_metric_id TO auto_calculated_indicator_id;
ALTER TABLE funder.published_system_metric_targets RENAME COLUMN system_metric_id TO auto_calculated_indicator_id;

-- tables
ALTER TABLE accelerator.system_metrics RENAME TO auto_calculated_indicators;
ALTER TABLE accelerator.report_system_metrics RENAME TO report_auto_calculated_indicators;
ALTER TABLE funder.published_report_system_metrics RENAME TO published_report_auto_calculated_indicators;
ALTER TABLE accelerator.report_system_metric_targets RENAME TO report_auto_calculated_indicator_targets;
ALTER TABLE funder.published_system_metric_targets RENAME TO published_auto_calculated_indicator_targets;

ALTER SEQUENCE accelerator.system_metrics_id_seq RENAME TO auto_calculated_indicators_id_seq;

-- constraints
ALTER TABLE accelerator.auto_calculated_indicators RENAME CONSTRAINT system_metrics_pkey TO auto_calculated_indicators_pkey;
ALTER TABLE accelerator.auto_calculated_indicators RENAME CONSTRAINT system_metrics_type_id_fkey TO auto_calculated_indicators_type_id_fkey;
ALTER TABLE accelerator.auto_calculated_indicators RENAME CONSTRAINT system_metrics_component_id_fkey TO auto_calculated_indicators_component_id_fkey;

ALTER TABLE accelerator.report_auto_calculated_indicators RENAME CONSTRAINT report_system_metrics_pkey TO report_auto_calculated_indicators_pkey;
ALTER TABLE accelerator.report_auto_calculated_indicators RENAME CONSTRAINT report_system_metrics_report_id_fkey TO report_auto_calculated_indicators_report_id_fkey;
ALTER TABLE accelerator.report_auto_calculated_indicators RENAME CONSTRAINT report_system_metrics_system_metric_id_fkey TO report_auto_calculated_indicators_auto_calculated_indicator_id_fkey;
ALTER TABLE accelerator.report_auto_calculated_indicators RENAME CONSTRAINT report_system_metrics_modified_by_fkey TO report_auto_calculated_indicators_modified_by_fkey;
ALTER TABLE accelerator.report_auto_calculated_indicators RENAME CONSTRAINT report_system_metrics_status_id_fkey TO report_auto_calculated_indicators_status_id_fkey;

ALTER TABLE funder.published_report_auto_calculated_indicators RENAME CONSTRAINT published_report_system_metrics_pkey TO published_report_auto_calculated_indicators_pkey;
ALTER TABLE funder.published_report_auto_calculated_indicators RENAME CONSTRAINT published_report_system_metrics_report_id_fkey TO published_report_auto_calculated_indicators_report_id_fkey;
ALTER TABLE funder.published_report_auto_calculated_indicators RENAME CONSTRAINT published_report_system_metrics_system_metric_id_fkey TO published_report_auto_calculated_indicators_auto_calculated_indicator_id_fkey;
ALTER TABLE funder.published_report_auto_calculated_indicators RENAME CONSTRAINT published_report_system_metrics_status_id_fkey TO published_report_auto_calculated_indicators_status_id_fkey;

ALTER TABLE accelerator.report_auto_calculated_indicator_targets RENAME CONSTRAINT report_system_metric_targets_pkey TO report_auto_calculated_indicator_targets_pkey;
ALTER TABLE accelerator.report_auto_calculated_indicator_targets RENAME CONSTRAINT report_system_metric_targets_project_id_fkey TO report_auto_calculated_indicator_targets_project_id_fkey;
ALTER TABLE accelerator.report_auto_calculated_indicator_targets RENAME CONSTRAINT report_system_metric_targets_system_metric_id_fkey TO report_auto_calculated_indicator_targets_auto_calculated_indicator_id_fkey;

ALTER TABLE funder.published_auto_calculated_indicator_targets RENAME CONSTRAINT published_system_metric_targets_pkey TO published_auto_calculated_indicator_targets_pkey;
ALTER TABLE funder.published_auto_calculated_indicator_targets RENAME CONSTRAINT published_system_metric_targets_project_id_fkey TO published_auto_calculated_indicator_targets_project_id_fkey;
ALTER TABLE funder.published_auto_calculated_indicator_targets RENAME CONSTRAINT published_system_metric_targets_system_metric_id_fkey TO published_auto_calculated_indicator_targets_auto_calculated_indicator_id_fkey;

-- indexes
ALTER INDEX accelerator.report_system_metrics_system_metric_id_idx RENAME TO report_auto_calculated_indicators_auto_calculated_indicator_id_idx;
ALTER INDEX accelerator.report_system_metric_targets_project_id_year_idx RENAME TO report_auto_calculated_indicator_targets_project_id_year_idx;
ALTER INDEX funder.published_system_metric_targets_project_id_year_idx RENAME TO published_auto_calculated_indicator_targets_project_id_year_idx;
