-- standard_indicator_id columns
ALTER TABLE accelerator.report_standard_indicators RENAME COLUMN standard_indicator_id TO common_indicator_id;
ALTER TABLE funder.published_report_standard_indicators RENAME COLUMN standard_indicator_id TO common_indicator_id;
ALTER TABLE accelerator.report_standard_indicator_targets RENAME COLUMN standard_indicator_id TO common_indicator_id;
ALTER TABLE funder.published_standard_indicator_targets RENAME COLUMN standard_indicator_id TO common_indicator_id;

-- tables
ALTER TABLE accelerator.standard_indicators RENAME TO common_indicators;
ALTER TABLE accelerator.report_standard_indicators RENAME TO report_common_indicators;
ALTER TABLE funder.published_report_standard_indicators RENAME TO published_report_common_indicators;
ALTER TABLE accelerator.report_standard_indicator_targets RENAME TO report_common_indicator_targets;
ALTER TABLE funder.published_standard_indicator_targets RENAME TO published_common_indicator_targets;

ALTER SEQUENCE accelerator.standard_indicators_id_seq RENAME TO common_indicators_id_seq;

-- constraints
ALTER TABLE accelerator.common_indicators RENAME CONSTRAINT standard_indicators_pkey TO common_indicators_pkey;
ALTER TABLE accelerator.common_indicators RENAME CONSTRAINT standard_indicators_level_id_fkey TO common_indicators_level_id_fkey;
ALTER TABLE accelerator.common_indicators RENAME CONSTRAINT standard_indicators_category_id_fkey TO common_indicators_category_id_fkey;

ALTER TABLE accelerator.report_common_indicators RENAME CONSTRAINT report_standard_indicators_pkey TO report_common_indicators_pkey;
ALTER TABLE accelerator.report_common_indicators RENAME CONSTRAINT report_standard_indicators_report_id_fkey TO report_common_indicators_report_id_fkey;
ALTER TABLE accelerator.report_common_indicators RENAME CONSTRAINT report_standard_indicators_standard_indicator_id_fkey TO report_common_indicators_common_indicator_id_fkey;
ALTER TABLE accelerator.report_common_indicators RENAME CONSTRAINT report_standard_indicators_modified_by_fkey TO report_common_indicators_modified_by_fkey;
ALTER TABLE accelerator.report_common_indicators RENAME CONSTRAINT report_standard_indicators_status_id_fkey TO report_common_indicators_status_id_fkey;

ALTER TABLE funder.published_report_common_indicators RENAME CONSTRAINT published_report_standard_indicators_pkey TO published_report_common_indicators_pkey;
ALTER TABLE funder.published_report_common_indicators RENAME CONSTRAINT published_report_standard_indicators_report_id_fkey TO published_report_common_indicators_report_id_fkey;
ALTER TABLE funder.published_report_common_indicators RENAME CONSTRAINT published_report_standard_indicators_standard_indicator_id_fkey TO published_report_common_indicators_common_indicator_id_fkey;
ALTER TABLE funder.published_report_common_indicators RENAME CONSTRAINT published_report_standard_indicators_status_id_fkey TO published_report_common_indicators_status_id_fkey;

ALTER TABLE accelerator.report_common_indicator_targets RENAME CONSTRAINT report_standard_indicator_targets_pkey TO report_common_indicator_targets_pkey;
ALTER TABLE accelerator.report_common_indicator_targets RENAME CONSTRAINT report_standard_indicator_targets_project_id_fkey TO report_common_indicator_targets_project_id_fkey;
ALTER TABLE accelerator.report_common_indicator_targets RENAME CONSTRAINT report_standard_indicator_targets_standard_indicator_id_fkey TO report_common_indicator_targets_common_indicator_id_fkey;

ALTER TABLE funder.published_common_indicator_targets RENAME CONSTRAINT published_standard_indicator_targets_pkey TO published_common_indicator_targets_pkey;
ALTER TABLE funder.published_common_indicator_targets RENAME CONSTRAINT published_standard_indicator_targets_project_id_fkey TO published_common_indicator_targets_project_id_fkey;
ALTER TABLE funder.published_common_indicator_targets RENAME CONSTRAINT published_standard_indicator_targets_standard_indicator_id_fkey TO published_common_indicator_targets_common_indicator_id_fkey;

-- indexes
ALTER INDEX accelerator.report_standard_indicator_targets_project_id_year_idx RENAME TO report_common_indicator_targets_project_id_year_idx;
ALTER INDEX funder.published_standard_indicator_targets_project_id_year_idx RENAME TO published_common_indicator_targets_project_id_year_idx;
