CREATE TABLE accession_photo (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    accession_id BIGINT NOT NULL REFERENCES accession,
    filename TEXT NOT NULL,
    uploaded_time TIMESTAMP WITH TIME ZONE NOT NULL,
    captured_time TIMESTAMP WITH TIME ZONE NOT NULL,
    content_type TEXT NOT NULL,
    size INTEGER NOT NULL,
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    gps_accuracy INTEGER,

    UNIQUE (accession_id, filename)
);
