package com.terraformation.backend.customer.event

import com.terraformation.backend.db.FacilityId
import com.terraformation.backend.db.UserId

/**
 * Published when the device manager at a facility requests that an alert be broadcast to the
 * appropriate people. In that case, the content of the alert is supplied in the incoming request
 * from the device manager, rather than being generated by terraware-server.
 */
data class FacilityAlertRequestedEvent(
    val facilityId: FacilityId,
    val subject: String,
    val body: String,
    val requestedBy: UserId,
)
