CREATE TABLE participants (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE,
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX ON participants (created_by);
CREATE INDEX ON participants (modified_by);

ALTER TABLE projects ADD COLUMN participant_id BIGINT REFERENCES participants;

CREATE INDEX ON projects (participant_id);
