ALTER TABLE projects ADD UNIQUE (organization_id, id);

CREATE TABLE tracking.draft_planting_sites (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    organization_id BIGINT NOT NULL REFERENCES organizations ON DELETE CASCADE,
    project_id BIGINT REFERENCES projects ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    time_zone TEXT REFERENCES time_zones (time_zone),
    num_planting_zones INTEGER,
    num_planting_subzones INTEGER,
    data JSONB NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,

    -- Prevent pointing to projects in other organizations.
    FOREIGN KEY (organization_id, project_id) REFERENCES projects (organization_id, id)
);

CREATE INDEX ON tracking.draft_planting_sites (organization_id);
CREATE INDEX ON tracking.draft_planting_sites (project_id);
