# Simple service definitions for running the server in a local dev environment. This should
# not be used in production!

version: "2"

volumes:
  photo-data:

services:
  postgres:
    image: "postgres:12"
    environment:
      POSTGRES_DB: "terraware"
      POSTGRES_PASSWORD: "terraware"

  terraware-server:
    image: "terraware-server"
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/terraware"
      DATABASE_PASSWORD: "terraware"
      TERRAWARE_PHOTO_DIR: "/data/photos"
      TERRAWARE_USE_INTERNAL_STORAGE: "true"
    volumes:
      - "photo-data:/data/photos"
    depends_on:
      - "postgres"
