# Example configuration that runs Keycloak in a local development environment.
#
# This isn't suitable for production use!

version: "2"

services:
  keycloak:
    image: "quay.io/keycloak/keycloak:19.0.0"
    command: "start-dev"
    ports:
      # Keycloak listens on port 8080 by default, but so does terraware-server,
      # so remap it to host port 8081.
      - "8081:8080"
    restart: "on-failure"
    environment:
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
      - "WEB_APP_URL=http://localhost:3000/"
