ALTER TABLE tracking.observation_photo_positions RENAME TO observation_plot_positions;

CREATE TABLE tracking.observed_plot_coordinates (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    observation_id BIGINT NOT NULL REFERENCES tracking.observations ON DELETE CASCADE,
    monitoring_plot_id BIGINT NOT NULL REFERENCES tracking.monitoring_plots ON DELETE CASCADE,
    position_id INTEGER NOT NULL REFERENCES tracking.observation_plot_positions,
    gps_coordinates GEOMETRY(POINT) NOT NULL,

    FOREIGN KEY (observation_id, monitoring_plot_id)
        REFERENCES tracking.observation_plots (observation_id, monitoring_plot_id),
    CONSTRAINT one_point_per_position
        UNIQUE (observation_id, monitoring_plot_id, position_id)
);
