CREATE TABLE nursery.batch_photos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    batch_id BIGINT NOT NULL REFERENCES nursery.batches,
    file_id BIGINT REFERENCES files ON DELETE SET NULL,
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_by BIGINT REFERENCES users,
    deleted_time TIMESTAMP WITH TIME ZONE,

    UNIQUE (file_id)
);

CREATE INDEX ON nursery.batch_photos (batch_id);
