CREATE TABLE tracking.planting_site_notifications (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    planting_site_id BIGINT NOT NULL REFERENCES tracking.planting_sites ON DELETE CASCADE,
    notification_type_id INTEGER NOT NULL REFERENCES notification_types,
    notification_number INTEGER NOT NULL,
    sent_time TIMESTAMP WITH TIME ZONE NOT NULL,

    UNIQUE (planting_site_id, notification_type_id, notification_number)
);

-- These are also in R__TypeCodes.sql
INSERT INTO notification_criticalities (id, name)
VALUES (1, 'Info')
ON CONFLICT DO NOTHING;
INSERT INTO notification_types (id, name, notification_criticality_id)
VALUES (21, 'Observation Not Scheduled (Support)', 1);

INSERT INTO tracking.planting_site_notifications
    (planting_site_id, notification_type_id, notification_number, sent_time)
SELECT ps.id, nt.id, 1, ps.schedule_observation_notification_sent_time
FROM tracking.planting_sites ps, notification_types nt
WHERE ps.schedule_observation_notification_sent_time IS NOT NULL
AND nt.name = 'Schedule Observation';

INSERT INTO tracking.planting_site_notifications
    (planting_site_id, notification_type_id, notification_number, sent_time)
SELECT ps.id, nt.id, 2, ps.schedule_observation_reminder_notification_sent_time
FROM tracking.planting_sites ps, notification_types nt
WHERE ps.schedule_observation_reminder_notification_sent_time IS NOT NULL
AND nt.name = 'Schedule Observation';

INSERT INTO tracking.planting_site_notifications
    (planting_site_id, notification_type_id, notification_number, sent_time)
SELECT ps.id, nt.id, 1, ps.observation_not_scheduled_first_notification_sent_time
FROM tracking.planting_sites ps, notification_types nt
WHERE ps.observation_not_scheduled_first_notification_sent_time IS NOT NULL
AND nt.name = 'Observation Not Scheduled (Support)';

INSERT INTO tracking.planting_site_notifications
    (planting_site_id, notification_type_id, notification_number, sent_time)
SELECT ps.id, nt.id, 2, ps.observation_not_scheduled_second_notification_sent_time
FROM tracking.planting_sites ps, notification_types nt
WHERE ps.observation_not_scheduled_second_notification_sent_time IS NOT NULL
AND nt.name = 'Observation Not Scheduled (Support)';

-- Usually we would drop columns in a separate migration to avoid breaking the old code while the
-- new release is being rolled out, but in this case we do it all in one migration.
--
-- If notifications are being generated on another instance while this migration is running, the
-- notification job will fail because we're dropping these columns. The next run will generate
-- any missing notifications.
ALTER TABLE tracking.planting_sites DROP COLUMN observation_not_scheduled_first_notification_sent_time;
ALTER TABLE tracking.planting_sites DROP COLUMN observation_not_scheduled_second_notification_sent_time;
ALTER TABLE tracking.planting_sites DROP COLUMN schedule_observation_notification_sent_time;
ALTER TABLE tracking.planting_sites DROP COLUMN schedule_observation_reminder_notification_sent_time;
