CREATE TABLE tracking.planting_seasons (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    planting_site_id BIGINT NOT NULL REFERENCES tracking.planting_sites ON DELETE CASCADE,
    start_date DATE NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date DATE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    is_active BOOLEAN NOT NULL,

    CHECK (start_date < end_date),
    CHECK (start_time < end_time),

    CONSTRAINT one_active_per_site
        EXCLUDE (planting_site_id WITH =) WHERE (is_active = TRUE)
);

CREATE INDEX ON tracking.planting_seasons (planting_site_id);
CREATE INDEX ON tracking.planting_seasons (is_active, end_time);
CREATE INDEX ON tracking.planting_seasons (is_active, start_time, end_time);
