-- Add vote options enum table (YES, CONDITIONAL, NO)
CREATE TABLE accelerator.vote_options (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value TEXT NOT NULL,
    UNIQUE (value)
);

-- Add whitelisted voters per project
CREATE TABLE accelerator.project_voters (
    user_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
    project_id BIGINT NOT NULL REFERENCES projects ON DELETE CASCADE,
    PRIMARY KEY (user_id, project_id)
);

-- Add voting records
CREATE TABLE accelerator.project_vote_records (
    user_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
    project_id BIGINT NOT NULL REFERENCES projects ON DELETE CASCADE,
    vote_option_id BIGINT NOT NULL REFERENCES accelerator.vote_options,
    conditional_info TEXT,
    PRIMARY KEY (user_id, project_id)
);

-- Speed up query by projects
CREATE INDEX ON accelerator.project_voters(project_id);
CREATE INDEX ON accelerator.project_vote_records(project_id);

