package com.terraformation.backend.accelerator.model

import com.terraformation.backend.db.default_schema.LandUseModelType
import com.terraformation.backend.db.default_schema.ProjectId
import com.terraformation.backend.db.default_schema.Region
import java.math.BigDecimal

/** Data class to hold project variable values. */
data class ProjectAcceleratorVariableValuesModel(
    val accumulationRate: BigDecimal? = null,
    val annualCarbon: BigDecimal? = null,
    val applicationReforestableLand: BigDecimal? = null,
    val carbonCapacity: BigDecimal? = null,
    val clickUpLink: String? = null,
    val confirmedReforestableLand: BigDecimal? = null,
    val countryCode: String? = null,
    val dealDescription: String? = null,
    val dealName: String? = null,
    val expectedMarketCredits: BigDecimal? = null,
    val failureRisk: String? = null,
    val gisReportsLink: String? = null,
    val investmentThesis: String? = null,
    val landUseModelTypes: Set<LandUseModelType> = emptySet(),
    val landUseModelHectares: Map<LandUseModelType, BigDecimal> = emptyMap(),
    val maxCarbonAccumulation: BigDecimal? = null,
    val methodologyNumber: String? = null,
    val minCarbonAccumulation: BigDecimal? = null,
    val minProjectArea: BigDecimal? = null,
    val numNativeSpecies: Int? = null,
    val perHectareBudget: BigDecimal? = null,
    val projectArea: BigDecimal? = null,
    val projectId: ProjectId,
    val riskTrackerLink: String? = null,
    val sdgList: Set<SustainableDevelopmentGoal> = emptySet(),
    val slackLink: String? = null,
    val standard: String? = null,
    val region: Region? = null,
    val totalCarbon: BigDecimal? = null,
    val totalExpansionPotential: BigDecimal? = null,
    val totalVCU: BigDecimal? = null,
    val verraLink: String? = null,
    val whatNeedsToBeTrue: String? = null,
) {

  fun toProjectAcceleratorDetails() =
      ProjectAcceleratorDetailsModel(
          accumulationRate = accumulationRate,
          annualCarbon = annualCarbon,
          applicationReforestableLand = applicationReforestableLand,
          carbonCapacity = carbonCapacity,
          clickUpLink = clickUpLink,
          confirmedReforestableLand = confirmedReforestableLand,
          countryCode = countryCode,
          dealDescription = dealDescription,
          dealName = dealName,
          expectedMarketCredits = expectedMarketCredits,
          failureRisk = failureRisk,
          gisReportsLink = gisReportsLink,
          investmentThesis = investmentThesis,
          landUseModelTypes = landUseModelTypes,
          landUseModelHectares = landUseModelHectares,
          maxCarbonAccumulation = maxCarbonAccumulation,
          methodologyNumber = methodologyNumber,
          minCarbonAccumulation = minCarbonAccumulation,
          minProjectArea = minProjectArea,
          numNativeSpecies = numNativeSpecies,
          perHectareBudget = perHectareBudget,
          projectArea = projectArea,
          projectId = projectId,
          riskTrackerLink = riskTrackerLink,
          sdgList = sdgList,
          slackLink = slackLink,
          standard = standard,
          region = region,
          totalCarbon = totalCarbon,
          totalExpansionPotential = totalExpansionPotential,
          totalVCU = totalVCU,
          verraLink = verraLink,
          whatNeedsToBeTrue = whatNeedsToBeTrue,
      )
}
