CREATE TABLE tracking.planting_site_histories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    planting_site_id BIGINT NOT NULL REFERENCES tracking.planting_sites ON DELETE CASCADE,
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    boundary GEOMETRY(MultiPolygon) NOT NULL,
    grid_origin GEOMETRY(Point),
    exclusion GEOMETRY(MultiPolygon)
);

CREATE INDEX ON tracking.planting_site_histories (planting_site_id);

CREATE TABLE tracking.planting_zone_histories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    planting_site_history_id BIGINT NOT NULL REFERENCES tracking.planting_site_histories ON DELETE CASCADE,
    planting_zone_id BIGINT REFERENCES tracking.planting_zones ON DELETE SET NULL,
    name TEXT NOT NULL,
    boundary GEOMETRY(MultiPolygon) NOT NULL
);

CREATE INDEX ON tracking.planting_zone_histories (planting_site_history_id);
CREATE INDEX ON tracking.planting_zone_histories (planting_zone_id);

CREATE TABLE tracking.planting_subzone_histories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    planting_zone_history_id BIGINT NOT NULL REFERENCES tracking.planting_zone_histories ON DELETE CASCADE,
    planting_subzone_id BIGINT REFERENCES tracking.planting_subzones ON DELETE SET NULL,
    name TEXT NOT NULL,
    full_name TEXT NOT NULL,
    boundary GEOMETRY(MultiPolygon) NOT NULL
);

CREATE INDEX ON tracking.planting_subzone_histories (planting_zone_history_id);
CREATE INDEX ON tracking.planting_subzone_histories (planting_subzone_id);
