CREATE TABLE accelerator.participant_project_species (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_id BIGINT REFERENCES public.projects ON DELETE CASCADE,
    species_id BIGINT REFERENCES public.species ON DELETE CASCADE,
    submission_status_id INTEGER NOT NULL REFERENCES accelerator.submission_statuses,
    feedback TEXT,
    rationale TEXT,

    UNIQUE (project_id, species_id)
);

CREATE INDEX ON accelerator.participant_project_species (project_id);
