CREATE TABLE document_producer.methodologies (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,

    UNIQUE (name)
);

CREATE TABLE document_producer.variable_types (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE document_producer.variables (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    variable_type_id INTEGER NOT NULL REFERENCES document_producer.variable_types,
    replaces_variable_id BIGINT REFERENCES document_producer.variables ON DELETE SET NULL,
    is_list BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT cannot_have_multiple_replacements
        UNIQUE (replaces_variable_id),

    -- Compound unique key so child tables can constrain themselves to variables of the correct type.
    UNIQUE (id, variable_type_id)
);

CREATE TABLE document_producer.variable_manifests (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    methodology_id BIGINT NOT NULL REFERENCES methodologies,
    created_by BIGINT NOT NULL DEFAULT -1 REFERENCES users ON DELETE SET DEFAULT,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE document_producer.variable_manifest_entries (
    variable_manifest_id BIGINT NOT NULL REFERENCES document_producer.variable_manifests,
    variable_id BIGINT NOT NULL REFERENCES document_producer.variables,
    position INTEGER NOT NULL,
    name TEXT NOT NULL,
    description TEXT,

    PRIMARY KEY (variable_manifest_id, variable_id),
    UNIQUE (variable_manifest_id, position),
    UNIQUE (variable_manifest_id, name)
);

CREATE TABLE document_producer.variable_numbers (
    variable_id BIGINT PRIMARY KEY REFERENCES document_producer.variables ON DELETE CASCADE,
    variable_type_id INTEGER NOT NULL REFERENCES document_producer.variable_types,
    min_value NUMERIC,
    max_value NUMERIC,
    decimal_places INTEGER NOT NULL DEFAULT 0,

    CHECK (variable_type_id = 1),

    FOREIGN KEY (variable_id, variable_type_id) REFERENCES document_producer.variables (id, variable_type_id)
);

CREATE TABLE document_producer.variable_text_types (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE document_producer.variable_texts (
    variable_id BIGINT PRIMARY KEY,
    variable_type_id INTEGER NOT NULL REFERENCES document_producer.variable_types,
    variable_text_type_id INTEGER NOT NULL REFERENCES document_producer.variable_text_types,

    CHECK (variable_type_id = 2),

    FOREIGN KEY (variable_id, variable_type_id) REFERENCES document_producer.variables (id, variable_type_id) ON DELETE CASCADE
);

CREATE TABLE document_producer.variable_images (
    variable_id BIGINT PRIMARY KEY,
    variable_type_id INTEGER NOT NULL REFERENCES document_producer.variable_types,
    title_required BOOLEAN NOT NULL,

    CHECK (variable_type_id = 4),

    FOREIGN KEY (variable_id, variable_type_id) REFERENCES document_producer.variables (id, variable_type_id) ON DELETE CASCADE
);

CREATE TABLE document_producer.variable_sections (
    variable_id BIGINT PRIMARY KEY,
    variable_type_id INTEGER NOT NULL REFERENCES document_producer.variable_types,
    parent_variable_id BIGINT,
    parent_variable_type_id INTEGER REFERENCES document_producer.variable_types,
    position INTEGER NOT NULL,
    render_heading BOOLEAN NOT NULL DEFAULT TRUE,

    CHECK (variable_type_id = 8),
    CHECK (parent_variable_type_id IS NULL OR parent_variable_type_id = 8),

    CONSTRAINT no_duplicate_positions_under_parent
        UNIQUE (parent_variable_id, position),

    FOREIGN KEY (variable_id, variable_type_id) REFERENCES document_producer.variables (id, variable_type_id) ON DELETE CASCADE,
    FOREIGN KEY (parent_variable_id, parent_variable_type_id) REFERENCES document_producer.variables (id, variable_type_id) ON DELETE CASCADE
);

CREATE TABLE document_producer.variable_selects (
    variable_id BIGINT PRIMARY KEY,
    variable_type_id INTEGER NOT NULL REFERENCES document_producer.variable_types,
    is_multiple BOOLEAN NOT NULL,

    CHECK (variable_type_id = 5),

    UNIQUE (variable_id, variable_type_id),

    FOREIGN KEY (variable_id, variable_type_id) REFERENCES document_producer.variables (id, variable_type_id) ON DELETE CASCADE
);

CREATE TABLE document_producer.variable_select_options (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    variable_id BIGINT NOT NULL REFERENCES document_producer.variables ON DELETE CASCADE,
    variable_type_id INTEGER NOT NULL REFERENCES document_producer.variable_types,
    position INTEGER NOT NULL,
    name TEXT NOT NULL,
    description TEXT,

    UNIQUE (id, variable_id),

    FOREIGN KEY (variable_id, variable_type_id) REFERENCES document_producer.variable_selects (variable_id, variable_type_id) ON DELETE CASCADE
);

CREATE TABLE document_producer.variable_table_columns (
    variable_id BIGINT PRIMARY KEY REFERENCES document_producer.variables,
    table_variable_id BIGINT NOT NULL REFERENCES document_producer.variables,
    table_variable_type_id INTEGER NOT NULL REFERENCES document_producer.variable_types,
    position INTEGER NOT NULL,

    CHECK (table_variable_type_id = 6),

    CONSTRAINT no_duplicate_column_positions
        UNIQUE (table_variable_id, position),

    FOREIGN KEY (table_variable_id, table_variable_type_id) REFERENCES document_producer.variable_selects (variable_id, variable_type_id) ON DELETE CASCADE
);

CREATE TABLE document_producer.variable_impacts (
    impacting_variable_id BIGINT NOT NULL REFERENCES document_producer.variables ON DELETE CASCADE,
    impacted_variable_id BIGINT NOT NULL REFERENCES document_producer.variables ON DELETE CASCADE,

    PRIMARY KEY (impacting_variable_id, impacted_variable_id),
    UNIQUE (impacted_variable_id, impacting_variable_id)
);
