CREATE TABLE document_producer.pdd_statuses (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE document_producer.pdds (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    methodology_id BIGINT NOT NULL REFERENCES document_producer.methodologies,
    variable_manifest_id BIGINT NOT NULL REFERENCES document_producer.variable_manifests,
    name TEXT NOT NULL,
    organization_name TEXT NOT NULL,
    status_id INTEGER NOT NULL REFERENCES document_producer.pdd_statuses,
    owned_by BIGINT NOT NULL DEFAULT -1 REFERENCES users ON DELETE SET DEFAULT,
    created_by BIGINT NOT NULL DEFAULT -1 REFERENCES users ON DELETE SET DEFAULT,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_by BIGINT NOT NULL DEFAULT -1 REFERENCES users ON DELETE SET DEFAULT,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,

    UNIQUE (name)
);

CREATE TABLE document_producer.pdd_saved_versions (
    pdd_id BIGINT NOT NULL REFERENCES document_producer.pdds ON DELETE CASCADE,
    variable_manifest_id BIGINT NOT NULL REFERENCES document_producer.variable_manifests,
    max_variable_value_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL DEFAULT -1 REFERENCES users ON DELETE SET DEFAULT,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    name TEXT,
    is_submitted BOOLEAN NOT NULL DEFAULT FALSE,
    is_accepted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE document_producer.variable_values (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pdd_id BIGINT NOT NULL REFERENCES document_producer.pdds ON DELETE CASCADE,
    variable_id BIGINT NOT NULL REFERENCES document_producer.variables,
    variable_type_id BIGINT NOT NULL REFERENCES document_producer.variable_types,
    index INTEGER NOT NULL DEFAULT 0,
    created_by BIGINT NOT NULL DEFAULT -1 REFERENCES users ON DELETE SET DEFAULT,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    verified_by BIGINT DEFAULT -1 REFERENCES users ON DELETE SET DEFAULT,
    verified_time TIMESTAMP WITH TIME ZONE,
    number_value NUMERIC,
    text_value TEXT,
    date_value DATE,

    CHECK (number_value IS NULL OR variable_type_id = 1),
    CHECK (text_value IS NULL OR variable_type_id = 2),

    -- Unique keys to allow child tables to enforce that values are for the right variables.
    UNIQUE (variable_id, id),
    UNIQUE (variable_id, variable_type_id, id),
    UNIQUE (pdd_id, id),

    FOREIGN KEY (variable_id, variable_type_id) REFERENCES document_producer.variables (id, variable_type_id)
);

CREATE TABLE document_producer.variable_image_values (
    variable_value_id BIGINT PRIMARY KEY REFERENCES document_producer.variable_values ON DELETE CASCADE,
    variable_id BIGINT NOT NULL REFERENCES document_producer.variables,
    variable_type_id INTEGER NOT NULL REFERENCES document_producer.variable_types,
    storage_url TEXT NOT NULL,
    caption TEXT,
    description TEXT,

    CHECK (variable_type_id = 4),

    FOREIGN KEY (variable_value_id, variable_id, variable_type_id) REFERENCES document_producer.variable_values (id, variable_id, variable_type_id)
);

CREATE TABLE document_producer.variable_link_values (
    variable_value_id BIGINT PRIMARY KEY REFERENCES document_producer.variable_values ON DELETE CASCADE,
    variable_id BIGINT NOT NULL REFERENCES document_producer.variables,
    variable_type_id INTEGER NOT NULL REFERENCES document_producer.variable_types,
    url TEXT NOT NULL,
    title TEXT NOT NULL,

    CHECK (variable_type_id = 7),

    FOREIGN KEY (variable_value_id, variable_id, variable_type_id) REFERENCES document_producer.variable_values (id, variable_id, variable_type_id)
);

CREATE TABLE document_producer.variable_section_values (
    variable_value_id BIGINT PRIMARY KEY REFERENCES document_producer.variable_values ON DELETE CASCADE,
    variable_id BIGINT NOT NULL REFERENCES document_producer.variables,
    variable_type_id INTEGER NOT NULL REFERENCES document_producer.variable_types,
    text_value TEXT,
    referenced_variable_id BIGINT REFERENCES document_producer.variables,
    referenced_variable_type_id INTEGER NOT NULL REFERENCES document_producer.variable_types,

    CONSTRAINT cannot_reference_other_sections
        CHECK (referenced_variable_type_id IS NULL OR referenced_variable_type_id <> 8),
    CONSTRAINT cannot_have_both_text_and_reference
        CHECK (text_value IS NULL OR referenced_variable_id IS NULL),
    CONSTRAINT must_have_text_or_reference
        CHECK (text_value IS NOT NULL OR referenced_variable_id IS NOT NULL),

    FOREIGN KEY (referenced_variable_id, referenced_variable_type_id) REFERENCES document_producer.variables (id, variable_type_id),
    FOREIGN KEY (variable_value_id, variable_id, variable_type_id) REFERENCES document_producer.variable_values (id, variable_id, variable_type_id)
);

CREATE INDEX ON document_producer.variable_section_values (referenced_variable_id);

CREATE TABLE document_producer.variable_select_option_values (
    variable_value_id BIGINT REFERENCES document_producer.variable_values ON DELETE CASCADE,
    variable_id BIGINT NOT NULL REFERENCES document_producer.variable_selects,
    variable_type_id INTEGER NOT NULL REFERENCES document_producer.variable_types,
    option_id BIGINT NOT NULL REFERENCES document_producer.variable_select_options,

    PRIMARY KEY (variable_value_id, option_id),

    CHECK (variable_type_id = 5),

    FOREIGN KEY (option_id, variable_id) REFERENCES document_producer.variable_select_options (id, variable_id),
    FOREIGN KEY (variable_value_id, variable_id, variable_type_id) REFERENCES document_producer.variable_values (id, variable_id, variable_type_id)
);

CREATE TABLE document_producer.variable_value_table_rows (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    variable_value_id BIGINT NOT NULL REFERENCES document_producer.variable_values ON DELETE CASCADE,
    table_row_value_id BIGINT NOT NULL REFERENCES document_producer.variable_values ON DELETE CASCADE,

    UNIQUE (variable_value_id, table_row_value_id)
);

CREATE INDEX ON document_producer.variable_value_table_rows (table_row_value_id);

CREATE VIEW document_producer.variable_current_values AS
    SELECT DISTINCT ON (variable_id, index)
        *
    FROM document_producer.variable_values
    ORDER BY variable_id, index, id DESC;

CREATE TABLE document_producer.variable_value_citations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    variable_value_id BIGINT NOT NULL REFERENCES document_producer.variable_values ON DELETE CASCADE,
    name TEXT NOT NULL,
    url TEXT
);

CREATE INDEX ON document_producer.variable_value_citations (variable_value_id);
