CREATE SCHEMA IF NOT EXISTS docprod;

ALTER TABLE documents SET SCHEMA docprod;
ALTER TABLE document_saved_versions SET SCHEMA docprod;
ALTER TABLE document_statuses SET SCHEMA docprod;
ALTER TABLE methodologies SET SCHEMA docprod;
ALTER TABLE variables SET SCHEMA docprod;
ALTER TABLE variable_image_values SET SCHEMA docprod;
ALTER TABLE variable_injection_display_styles SET SCHEMA docprod;
ALTER TABLE variable_link_values SET SCHEMA docprod;
ALTER TABLE variable_manifests SET SCHEMA docprod;
ALTER TABLE variable_manifest_entries SET SCHEMA docprod;
ALTER TABLE variable_numbers SET SCHEMA docprod;
ALTER TABLE variable_sections SET SCHEMA docprod;
ALTER TABLE variable_section_recommendations SET SCHEMA docprod;
ALTER TABLE variable_section_values SET SCHEMA docprod;
ALTER TABLE variable_selects SET SCHEMA docprod;
ALTER TABLE variable_select_options SET SCHEMA docprod;
ALTER TABLE variable_select_option_values SET SCHEMA docprod;
ALTER TABLE variable_tables SET SCHEMA docprod;
ALTER TABLE variable_table_columns SET SCHEMA docprod;
ALTER TABLE variable_table_styles SET SCHEMA docprod;
ALTER TABLE variable_texts SET SCHEMA docprod;
ALTER TABLE variable_text_types SET SCHEMA docprod;
ALTER TABLE variable_types SET SCHEMA docprod;
ALTER TABLE variable_usage_types SET SCHEMA docprod;
ALTER TABLE variable_values SET SCHEMA docprod;
ALTER TABLE variable_value_table_rows SET SCHEMA docprod
