CREATE TABLE docprod.variable_workflow_statuses (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE docprod.variable_workflow_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_id BIGINT NOT NULL REFERENCES projects ON DELETE CASCADE,
    variable_id BIGINT NOT NULL REFERENCES docprod.variables,
    max_variable_value_id BIGINT NOT NULL REFERENCES docprod.variable_values,
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    variable_workflow_status_id INTEGER NOT NULL REFERENCES docprod.variable_workflow_statuses,
    feedback TEXT,
    internal_comment TEXT
);

CREATE INDEX ON docprod.variable_workflow_history (project_id, variable_id, id DESC);
CREATE INDEX ON docprod.variable_workflow_history (variable_id);
CREATE INDEX ON docprod.variable_workflow_history (max_variable_value_id);
CREATE INDEX ON docprod.variable_workflow_history (created_by);
