CREATE TABLE docprod.variable_section_default_values (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    variable_id BIGINT NOT NULL REFERENCES docprod.variables ON DELETE CASCADE,
    variable_type_id INTEGER NOT NULL REFERENCES docprod.variable_types,
    variable_manifest_id BIGINT NOT NULL REFERENCES docprod.variable_manifests ON DELETE CASCADE,
    list_position INTEGER NOT NULL,
    text_value TEXT,
    used_variable_id BIGINT REFERENCES docprod.variables ON DELETE CASCADE,
    used_variable_type_id INTEGER REFERENCES docprod.variable_types,
    usage_type_id INTEGER REFERENCES docprod.variable_usage_types,
    display_style_id INTEGER REFERENCES docprod.variable_injection_display_styles,

    UNIQUE (variable_manifest_id, variable_id, list_position),

    CHECK (variable_type_id = 8),

    CONSTRAINT cannot_reference_other_sections
     CHECK (used_variable_type_id IS NULL OR used_variable_type_id <> 8),
    CONSTRAINT cannot_have_both_text_and_reference
     CHECK (text_value IS NULL OR used_variable_id IS NULL),
    CONSTRAINT must_have_text_or_reference
     CHECK (text_value IS NOT NULL OR used_variable_id IS NOT NULL),

    FOREIGN KEY (variable_id, variable_type_id) REFERENCES docprod.variables (id, variable_type_id),
    FOREIGN KEY (used_variable_id, used_variable_type_id) REFERENCES docprod.variables (id, variable_type_id)
);
