ALTER TABLE variable_section_recommendations DROP CONSTRAINT variable_section_recommendations_pkey;
ALTER TABLE variable_section_recommendations ADD PRIMARY KEY (section_variable_id, variable_manifest_id, recommended_variable_id);
