-- Schema documentation. The comments here are included in the generated HTML documentation that is
-- produced by SchemaDocsGenerator.
--
-- This migration is run by Flyway whenever it changes. It runs after all the numbered migrations,
-- so it's fine to add comments here in the same commit where you're creating new tables or columns.
--
-- Comments can use Markdown syntax.
--
-- Put "(Enum)" at the beginnings of comments on tables that define a fixed set of values.

COMMENT ON TABLE accession_germination_test_types IS '(Enum) Types of tests that can be performed on seeds to determine whether or not they successfully germinate';

COMMENT ON TABLE accession_notification_types IS '(Enum) Types of seed bank notification that can be generated by the application.';

COMMENT ON TABLE accession_notifications IS 'Notifications about tasks that need to be performed at a seed bank.';
COMMENT ON COLUMN accession_notifications.accession_id IS 'Null if this notification is not specific to a single accession.';
COMMENT ON COLUMN accession_notifications.accession_state_id IS 'For state notifications, which state is being notified about. Null otherwise.';

COMMENT ON TABLE accession_photos IS 'Linking table between `accessions` and `photos`.';

COMMENT ON TABLE accession_secondary_collectors IS 'Associates additional collectors with accessions. The primary collector is not included here, but is instead stored in `accessions.primary_collector_id`.';

COMMENT ON TABLE accession_state_history IS 'Historical record of when accessions moved to different states. A row is inserted here for every state transition.';
COMMENT ON COLUMN accession_state_history.old_state_id IS 'Null if this is the initial state for a new accession.';

COMMENT ON TABLE accession_states IS '(Enum) Available states an accession can be in. Each state represents a step in the seed management workflow.';

COMMENT ON TABLE accessions IS 'Information about batches of seeds. An accession is a batch of seeds of the same species collected in the same time and place by the same people.';
COMMENT ON COLUMN accessions.latest_viability_percent IS 'Percent of seeds germinated in most recent viability test, or in cut test if no germinations exist yet';
COMMENT ON COLUMN accessions.number IS 'Displayed as the accession number to the user.';
COMMENT ON COLUMN accessions.nursery_start_date IS 'When the accession was moved to a nursery, or null if it is not in a nursery.';
COMMENT ON COLUMN accessions.target_storage_condition IS 'The intended storage condition of the accession as determined during initial processing.';
COMMENT ON COLUMN accessions.total_viability_percent IS 'Percentage of viable seeds across all tests.';

COMMENT ON TABLE app_devices IS 'Installations of the mobile app that were used to upload seed data.';

COMMENT ON TABLE automations IS 'Configuration of automatic processes run by the device manager.';

COMMENT ON TABLE bags IS 'Individual bags of seeds that are part of an accession. An accession can consist of multiple bags.';

COMMENT ON TABLE collectors IS 'People who participated in seed collection. Both primary and secondary collectors are included.';

COMMENT ON TABLE conservation_statuses IS '(Enum) UICN Red List categories defining the conservation status of a given species.';

COMMENT ON TABLE countries IS 'Country information per ISO-3166.';
COMMENT ON COLUMN countries.code IS 'ISO-3166 alpha-2 country code.';
COMMENT ON COLUMN countries.name IS 'Name of country in US English.';

COMMENT ON TABLE country_subdivisions IS 'Country subdivision (state, province, region, etc.) information per ISO-3166-2.';
COMMENT ON COLUMN country_subdivisions.code IS 'Full ISO-3166-2 subdivision code including country code prefix.';
COMMENT ON COLUMN country_subdivisions.country_code IS 'ISO-3166 alpha-2 country code.';
COMMENT ON COLUMN country_subdivisions.name IS 'Name of subdivision in US English.';

COMMENT ON TABLE devices IS 'Hardware devices managed by the device manager at a facility.';

COMMENT ON TABLE facilities IS 'Physical locations at a site. For example, each seed bank and each nursery is a facility.';
COMMENT ON COLUMN facilities.idle_after_time IS 'Time at which the facility will be considered idle if no timeseries data is received. Null if the timeseries has already been marked as idle or if no timeseries data has ever been received from the facility.';
COMMENT ON COLUMN facilities.idle_since_time IS 'Time at which the facility became idle. Null if the facility is not currently considered idle.';
COMMENT ON COLUMN facilities.last_timeseries_time IS 'When the most recent timeseries data was received from the facility.';
COMMENT ON COLUMN facilities.max_idle_minutes IS 'Send an alert if this many minutes pass without new timeseries data from a facility''s device manager.';

COMMENT ON TABLE facility_types IS '(Enum) Types of facilities that can be represented in the data model.';

COMMENT ON TABLE flyway_schema_history IS 'Tracks which database migrations have already been applied. Used by the Flyway library, not by application.';

COMMENT ON TABLE gbif_distributions IS 'Information about geographic distribution of species and their conservation statuses.';

COMMENT ON TABLE gbif_names IS 'Scientific and vernacular names from the GBIF backbone dataset. Names are not required to be unique.';

COMMENT ON TABLE gbif_name_words IS 'Inverted index of lower-cased words from species and family names in the GBIF backbone dataset. Used to support fast per-word prefix searches.';

COMMENT ON TABLE gbif_taxa IS 'Taxonomic data about species and families. A subset of the GBIF backbone dataset.';

COMMENT ON TABLE gbif_vernacular_names IS 'Vernacular names for species and families. Part of the GBIF backbone dataset.';

COMMENT ON TABLE geolocations IS 'Locations where seeds were collected.';

COMMENT ON TABLE germination_seed_types IS '(Enum) Types of seeds that can be tested for germination ability. This refers to how the seeds were stored, not the physical characteristics of the seeds themselves.';

COMMENT ON TABLE germination_substrates IS '(Enum) Types of substrate that can be used to test seeds for germination ability.';

COMMENT ON TABLE germination_test_types IS '(Enum) Types of tests that can be performed on seeds to check for germination ability.';

COMMENT ON TABLE germination_tests IS 'Information about a single batch of seeds being tested for germination ability. This is the information about the test itself; the results are represented in the `germinations` table.';

COMMENT ON TABLE germination_treatments IS '(Enum) Techniques that can be used to treat seeds before testing them for germination ability.';

COMMENT ON TABLE germinations IS 'Result from a germination test of a batch of seeds. Germination tests can have multiple germinations, e.g., if different seeds germinate on different days.';

COMMENT ON TABLE organization_users IS 'Organization membership and role information.';

COMMENT ON TABLE organizations IS 'Top-level information about organizations.';
COMMENT ON COLUMN organizations.id IS 'Unique numeric identifier of the organization.';

COMMENT ON TABLE photos IS 'Generic information about individual photos. Photos are associated with application entities using linking tables such as `accession_photos`.';

COMMENT ON TABLE plant_forms IS '(Enum) What physical form a particular species takes. For example, "Tree" or "Shrub."';

COMMENT ON TABLE processing_methods IS '(Enum) Methods of counting seeds when processing accessions.';

COMMENT ON TABLE project_statuses IS '(Enum) Statuses of projects recognized by the application.';

COMMENT ON TABLE project_types IS '(Enum) Types of projects recognized by the application.';

COMMENT ON TABLE project_type_selections IS 'Which project types are selected for which projects.';

COMMENT ON TABLE project_users IS 'Linking table between `projects` and `users` defining which users are allowed to access which projects.';

COMMENT ON TABLE projects IS 'Information about a single restoration project. A project can span multiple sites.';
COMMENT ON COLUMN projects.hidden IS 'If true, the project and its associated sites and facilities should not be displayed to end users.';
COMMENT ON COLUMN projects.organization_wide IS 'If true, the project is accessible to the entire organization. If true, the project is only accessible to users who are added to it.';

COMMENT ON TABLE rare_types IS '(Enum) Possible values of the "Rare" attribute of an accession. This refers to whether the seed is rare at a site, not whether the species as a whole is rare or endangered.';

COMMENT ON TABLE roles IS '(Enum) Roles a user is allowed to have in an organization.';

COMMENT ON TABLE seed_quantity_units IS '(Enum) Available units in which seeds can be measured. For weight-based units, includes unit conversion information.';

COMMENT ON TABLE sites IS 'Physical locations where facilities are located or plants are being tracked.';
COMMENT ON COLUMN sites.locale IS 'Default locale at the site; an IETF BCP 47 language tag such as en-US.';
COMMENT ON COLUMN sites.timezone IS 'Name of time zone at site; an IANA tz database zone name.';

COMMENT ON TABLE source_plant_origins IS '(Enum) Types of origins of plants from which seeds were collected. For example, "Outplant" represents a plant that was cultivated, as opposed to one growing in the wild.';

COMMENT ON TABLE spatial_ref_sys IS '(Enum) Metadata about spatial reference (coordinate) systems. Managed by the PostGIS extension, not the application.';

COMMENT ON TABLE species IS 'Information about plant species that isn''t organization-specific. Currently, the application doesn''t have a way to share species across organizations, but we expect to want to be able to do that in the future so the data model allows it.';
COMMENT ON COLUMN species.name IS 'Primary name of the species. Currently, this is always the same as `species_names.name`.';
COMMENT ON COLUMN species.tsn IS '(Unused in current app version) Taxonomic Serial Number from the ITIS database, to link this species to its ITIS database entry.';
COMMENT ON COLUMN species.is_scientific IS 'If true, the `name` column is a scientific name.';

COMMENT ON TABLE species_endangered_types IS '(Enum) Possible values for the "Endangered" attribute of an accession. This is not used for plants whose locations are being tracked; see `conservation_statuses` instead.';

COMMENT ON TABLE species_names IS 'Per-organization names for species. A species can have multiple names, e.g., a scientific name and several common names, though the app currently does not provide a way to add multiple names. The primary name is stored here as well as in `species`. If multiple organizations use the same species, each one will have a separate row in this table.';
COMMENT ON COLUMN species_names.name IS 'Species name. This can be a scientific name or an arbitrary organization-supplied name in any language.';
COMMENT ON COLUMN species_names.is_scientific IS 'If true, the `name` column is a scientific name. There can be more than one scientific name for a species, though the app currently does not provide a way to add multiple names.';

COMMENT ON TABLE species_options IS 'Linking table between `species` and `organizations` that represents which species are available as options in the UI for a particular organization. When a species is deleted from an organization, its row in this table is deleted.';

COMMENT ON TABLE spring_session IS 'Active login sessions. Used by Spring Session, not the application.';

COMMENT ON TABLE spring_session_attributes IS 'Data associated with a login session. Used by Spring Session, not the application.';

COMMENT ON TABLE storage_conditions IS '(Enum) Refrigeration condition of seeds during storage.';

COMMENT ON TABLE storage_locations IS 'The available locations where seeds can be stored at a seed bank facility.';
COMMENT ON COLUMN storage_locations.name IS 'E.g., Freezer 1, Freezer 2';

COMMENT ON TABLE task_processed_times IS 'Tracks the most recently processed time for recurring tasks that need to cover non-overlapping time periods.';

COMMENT ON TABLE test_clock IS 'User-adjustable clock for test environments. Not used in production.';
COMMENT ON COLUMN test_clock.fake_time IS 'What time the server should believe it was at the time the row was written.';
COMMENT ON COLUMN test_clock.real_time IS 'What time it was in the real world when the row was written.';

COMMENT ON TABLE thumbnails IS 'Information about scaled-down versions of photos.';

COMMENT ON TABLE timeseries IS 'Properties of a series of values collected from a device. Each device metric is represented as a timeseries.';
COMMENT ON COLUMN timeseries.decimal_places IS 'For numeric timeseries, the number of digits after the decimal point to display.';
COMMENT ON COLUMN timeseries.units IS 'For numeric timeseries, the units represented by the values; unit names should be short (possibly abbreviations) and in the default language of the site.';

COMMENT ON TABLE timeseries_types IS '(Enum) Data formats of the values of a timeseries.';

COMMENT ON TABLE timeseries_values IS 'Individual data points on a timeseries. For example, each time the temperature is read from a thermometer, the reading is inserted here.';

COMMENT ON TABLE user_types IS '(Enum) Types of users. Most users are of type 1, "Individual."';

COMMENT ON TABLE users IS 'User identities. A user can be associated with organizations via `organization_users`.';
COMMENT ON COLUMN users.auth_id IS 'Unique identifier of the user in the authentication system. Currently, this is a Keycloak user ID.';
COMMENT ON COLUMN users.email_notifications_enabled IS 'If true, the user wants to receive notifications via email.';
COMMENT ON COLUMN users.last_activity_time IS 'When the user most recently interacted with the system.';

COMMENT ON TABLE withdrawal_purposes IS '(Enum) Reasons that someone can withdraw seeds from a seed bank.';

COMMENT ON TABLE withdrawals IS 'Information about seeds that have been withdrawn from a seed bank. Each time someone withdraws seeds, a new row is inserted here.';
