DROP TABLE IF EXISTS scheduled_job;

CREATE TABLE scheduled_job (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    scheduled_time TIMESTAMP WITH TIME ZONE NOT NULL,
    payload_class TEXT NOT NULL,
    payload_data jsonb NOT NULL,
    payload_version INTEGER NOT NULL,
    started_time TIMESTAMP WITH TIME ZONE,
    failure_message TEXT,
    failure_details TEXT
);

CREATE INDEX ON scheduled_job (scheduled_time);

COMMENT ON TABLE scheduled_job
    IS 'Work that should be performed at some time in the future.';
COMMENT ON COLUMN scheduled_job.started_time
    IS 'When the job started being executed. If null, job has not been started yet.';
COMMENT ON COLUMN scheduled_job.payload_class
    IS 'Fully qualified class name of job payload.';
COMMENT ON COLUMN scheduled_job.payload_version
    IS 'Version of the payload class at the time the job was scheduled; may be used to properly handle existing jobs if the payload definition is changed.';
COMMENT ON COLUMN scheduled_job.failure_message
    IS 'Short human-readable message describing why the job failed.';
COMMENT ON COLUMN scheduled_job.failure_details
    IS 'Technical details (stack trace, etc.) for debugging failed jobs.';

