CREATE TABLE project_types (
    id INTEGER PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE project_statuses (
    id INTEGER PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations,
    name TEXT NOT NULL,
    description TEXT,
    location TEXT,
    type_id INTEGER REFERENCES project_types (id),
    status_id INTEGER REFERENCES project_statuses (id),
    start_date DATE,
    end_date DATE,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,
    disabled_time TIMESTAMP WITH TIME ZONE
);

-- Existing sites don't have projects, so generate a default one for each site.
INSERT INTO projects (organization_id, name, created_time, modified_time)
SELECT organization_id, name, NOW(), NOW()
FROM sites;

ALTER TABLE sites ADD COLUMN project_id BIGINT REFERENCES projects (id);

UPDATE sites s
SET project_id = (SELECT id
                  FROM projects p
                  WHERE p.organization_id = s.organization_id AND p.name = s.name)
WHERE project_id IS NULL;

ALTER TABLE sites ALTER COLUMN project_id SET NOT NULL;

ALTER TABLE sites DROP COLUMN organization_id;
