CREATE TABLE facility_alert_recipients (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    facility_id BIGINT NOT NULL REFERENCES facilities,
    email TEXT NOT NULL,
    UNIQUE (facility_id, email)
);
