CREATE TABLE gbif_taxa (
    taxon_id BIGINT PRIMARY KEY,
    dataset_id TEXT,
    parent_name_usage_id BIGINT,
    accepted_name_usage_id BIGINT,
    original_name_usage_id BIGINT,
    scientific_name TEXT NOT NULL,
    canonical_name TEXT,
    generic_name TEXT,
    specific_epithet TEXT,
    infraspecific_epithet TEXT,
    taxon_rank TEXT NOT NULL,
    taxonomic_status TEXT NOT NULL,
    nomenclatural_status TEXT,
    phylum TEXT,
    "class" TEXT,
    "order" TEXT,
    family TEXT,
    genus TEXT
);

CREATE TABLE gbif_vernacular_names (
    taxon_id BIGINT NOT NULL,
    vernacular_name TEXT NOT NULL,
    "language" TEXT,
    country_code TEXT
);

CREATE INDEX ON gbif_vernacular_names (taxon_id);

CREATE TABLE gbif_distributions (
    taxon_id BIGINT NOT NULL,
    country_code TEXT,
    establishment_means TEXT,
    occurrence_status TEXT,
    threat_status TEXT
);

CREATE INDEX ON gbif_distributions (taxon_id);

CREATE TABLE gbif_names (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    taxon_id BIGINT NOT NULL REFERENCES gbif_taxa (taxon_id),
    name TEXT NOT NULL,
    language TEXT,
    is_scientific BOOLEAN NOT NULL
);

CREATE INDEX ON gbif_names (taxon_id);

CREATE TABLE gbif_name_words (
    gbif_name_id BIGINT NOT NULL REFERENCES gbif_names,
    word TEXT NOT NULL
);

CREATE INDEX ON gbif_name_words (gbif_name_id);
CREATE INDEX ON gbif_name_words (word);
