CREATE TABLE notifications (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    notification_type_id INTEGER NOT NULL REFERENCES notification_types,
    user_id BIGINT NOT NULL REFERENCES users,
    organization_id BIGINT REFERENCES organizations,
    local_url TEXT NOT NULL,
    metadata JSONB NOT NULL,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    read_time TIMESTAMP WITH TIME ZONE
);
