CREATE TABLE device_managers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    balena_id BIGINT NOT NULL,
    balena_uuid ${uuidColumnType} NOT NULL,
    balena_modified_time TIMESTAMP WITH TIME ZONE NOT NULL,
    device_name TEXT NOT NULL,
    is_online BOOLEAN NOT NULL,
    last_connectivity_event TIMESTAMP WITH TIME ZONE,
    update_progress INTEGER,
    short_code TEXT NOT NULL,
    user_id BIGINT REFERENCES users,
    facility_id BIGINT REFERENCES facilities,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    refreshed_time TIMESTAMP WITH TIME ZONE NOT NULL,

    UNIQUE (balena_uuid),
    UNIQUE (facility_id),
    UNIQUE (short_code),
    CONSTRAINT device_managers_user_iff_facility CHECK (
        (user_id IS NOT NULL AND facility_id IS NOT NULL)
               OR (user_id IS NULL AND facility_id IS NULL))
);

CREATE INDEX ON device_managers (user_id);

CREATE TABLE facility_connection_states (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL
);

-- This needs to be here (in addition to R__TypeCodes.sql) so we can use it as the default value
-- in the ALTER TABLE statement.
INSERT INTO facility_connection_states (id, name) VALUES (1, 'Not Connected');

ALTER TABLE facilities ADD COLUMN
    connection_state_id INTEGER NOT NULL REFERENCES facility_connection_states (id) DEFAULT 1;
