CREATE TABLE disclaimers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    effective_on TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ON disclaimers(effective_on);

CREATE TABLE user_disclaimers (
    disclaimer_id BIGINT NOT NULL REFERENCES disclaimers ON DELETE CASCADE ,
    user_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
    accepted_on TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (disclaimer_id, user_id)
);
CREATE INDEX ON user_disclaimers(user_id);
