CREATE TABLE accession_quantity_history_types (
    id   INTEGER PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE accession_quantity_history (
    id                 BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    accession_id       BIGINT NOT NULL REFERENCES accessions ON DELETE CASCADE,
    history_type_id    INTEGER NOT NULL REFERENCES accession_quantity_history_types,
    created_by         BIGINT NOT NULL REFERENCES users,
    created_time       TIMESTAMP WITH TIME ZONE NOT NULL,
    remaining_quantity NUMERIC NOT NULL,
    remaining_units_id INTEGER NOT NULL REFERENCES seed_quantity_units
);

CREATE INDEX ON accession_quantity_history (accession_id);

ALTER TABLE accessions ADD COLUMN latest_observed_quantity NUMERIC;
ALTER TABLE accessions ADD COLUMN latest_observed_units_id INTEGER REFERENCES seed_quantity_units;
ALTER TABLE accessions ADD COLUMN latest_observed_time TIMESTAMP WITH TIME ZONE;

ALTER TABLE accessions ADD CONSTRAINT observed_quantity_must_have_time
CHECK (
    latest_observed_quantity IS NOT NULL AND latest_observed_time IS NOT NULL
    OR latest_observed_quantity IS NULL AND latest_observed_time IS NULL
);

ALTER TABLE accessions ADD CONSTRAINT observed_quantity_must_have_units
CHECK (
    latest_observed_quantity IS NOT NULL AND latest_observed_units_id IS NOT NULL
    OR latest_observed_quantity IS NULL AND latest_observed_units_id IS NULL
);

ALTER TABLE withdrawals ADD COLUMN estimated_count INTEGER;
ALTER TABLE withdrawals ADD COLUMN estimated_weight_quantity NUMERIC;
ALTER TABLE withdrawals ADD COLUMN estimated_weight_units_id INTEGER REFERENCES seed_quantity_units;

ALTER TABLE withdrawals ADD CONSTRAINT estimated_weight_must_have_units
CHECK (
    estimated_weight_quantity IS NOT NULL AND estimated_weight_units_id IS NOT NULL
    OR estimated_weight_quantity IS NULL AND estimated_weight_units_id IS NULL
);
