TREE_SPECIES = [
    # From https://en.wikipedia.org/wiki/Category:Trees_of_Africa
    "Acacia podalyriifolia",
    "Acacia sassa",
    "Adansonia digitata",
    "Afrocarpus dawei",
    "Afrocarpus falcatus",
    "Afrocarpus gracilior",
    "Afrocarpus usambarensis",
    "Afzelia bipindensis",
    "Afzelia pachyloba",
    "Afzelia quanzensis",
    "Albizia adianthifolia",
    "Albizia amara",
    "Albizia ferruginea",
    "Albizia gummifera",
    "Albizia obbiadensis",
    "Albizia vaughanii",
    "Aloe marlothii",
    "Androstachys",
    "Anogeissus leiocarpa",
    "Anonidium mannii",
    "Antrocaryon micraster",
    "Arbutus canariensis",
    "Aucoumea klaineana",
    "Avicennia germinans",
    "Baikiaea ghesquiereana",
    "Baikiaea insignis",
    "Baillonella",
    "Balanites aegyptiaca",
    "Balanites angolensis",
    "Balanites glabra",
    "Balanites pedicellaris",
    "Balanites rotundifolia",
    "Balanites wilsoniana",
    "Baphia nitida",
    "Bersama abyssinica",
    "Blighia sapida",
    "Bombax buonopozense",
    "Borassus aethiopum",
    "Boscia senegalensis",
    "Boswellia frereana",
    "Brachystegia",
    "Brachystegia angustistipulata",
    "Brachystegia bakeriana",
    "Brachystegia boehmii",
    "Brachystegia eurycoma",
    "Brachystegia glaucescens",
    "Brachystegia kennedyi",
    "Brachystegia laurentii",
    "Brachystegia nigerica",
    "Brachystegia spiciformis",
    "Brachystegia tamarindoides",
    "Brachystegia zenkeri",
    "Bridelia micrantha",
    "Faidherbia",
    "Ficus abutilifolia",
    "Ficus capreifolia",
    "Ficus cordata",
    "Ficus craterostoma",
    "Ficus exasperata",
    "Ficus faulkneriana",
    "Ficus glumosa",
    "Ficus ilicina",
    "Ficus ingens",
    "Ficus lateriflora",
    "Ficus natalensis",
    "Ficus polita",
    "Ficus salicifolia",
    "Ficus sansibarica",
    "Ficus sur",
    # https://en.wikipedia.org/wiki/Category:Trees_of_Asia
    "Abies sibirica",
    "Acer campestre",
    "Acer cappadocicum",
    "Acer platanoides",
    "Acer pseudosieboldianum",
    "Acer tataricum",
    "Ailanthus altissima",
    "Alnus alnobetula",
    "Alnus glutinosa",
    "Alnus incana",
    "Aralia elata",
    "Balanites aegyptiaca",
    "Carpinus betulus",
    "Carpinus orientalis",
    "Castanopsis cuspidata",
    "Celtis australis",
    "Chisocheton cumingianus subsp. balansae",
    "Crataegus monogyna",
    "Crateva adansonii",
    "Erythrina stricta",
    "Fagus orientalis",
    "Fagus × taurica",
    "Ficus amplissima",
    "Fraxinus excelsior 'Hessei'",
    "Fraxinus lanuginosa",
    "Gardenia tubifera",
    "Hezhang walnut",
    "Huanglong walnut",
    "Ilex aquifolium",
    "Ilex cornuta",
    "Juglans hopeiensis",
    "Juglans regia",
    "Jujube",
    "Juniperus foetidissima",
    "Larix gmelinii",
    "Pajanelia",
    "Pinus densata",
    "Pinus sylvestris",
    "Platanus orientalis",
    "Populus euphratica",
    "Populus sect. Aigeiros",
    "Quercus dentata",
    "Quercus franchetii",
    "Quercus glauca",
    "Quercus infectoria",
    "Quercus ramsbottomii",
    "Quercus robur",
    "Salix triandra",
    "Terminalia nitens",
    "Ulmus bergmanniana",
    "Ulmus bergmanniana var. bergmanniana",
    "Ulmus bergmanniana var. lasiophylla",
    "Ulmus boissieri",
    "Ulmus castaneifolia",
    "Ulmus changii var. changii",
    "Ulmus changii var. kunmingensis",
    "Ulmus chenmoui",
    "Ulmus davidiana",
    "Ulmus davidiana var. davidiana",
    "Ulmus davidiana var. japonica",
    "Ulmus elongata",
    "Ulmus glaucescens",
    "Ulmus glaucescens var. glaucescens",
    "Ulmus glaucescens var. lasiocarpa",
    "Ulmus harbinensis",
    "Ulmus laciniata",
    "Ulmus laciniata var. nikkoensis",
    "Ulmus macrocarpa",
    "Ulmus macrocarpa var. glabra",
    "Ulmus macrocarpa var. macrocarpa",
    "Ulmus microcarpa",
    "Ulmus minor subsp. canescens",
    "Ulmus prunifolia",
    "Ulmus pseudopropinqua",
    "Ulmus pumila 'Pinnato-ramosa'",
    "Ulmus szechuanica",
    "Yecheng walnut",
    "Ziziphus cambodiana",
    "Ziziphus jujuba",
    "Ziziphus spina-christi",
]

FIRST_NAMES = [
    "Brian",
    "Carlos",
    "Chris",
    "Constanza",
    "Jill",
    "Léann",
    "Peter",
    "Rachel",
    "Steve",
    "Yacin",
    "Yee",
    "Yishan",
]
