# From https://en.wikipedia.org/wiki/Category:Trees_of_Africa
TREE_SPECIES = [
    "Acacia podalyriifolia",
    "Acacia sassa",
    "Adansonia digitata",
    "Afrocarpus dawei",
    "Afrocarpus falcatus",
    "Afrocarpus gracilior",
    "Afrocarpus usambarensis",
    "Afzelia bipindensis",
    "Afzelia pachyloba",
    "Afzelia quanzensis",
    "Albizia adianthifolia",
    "Albizia amara",
    "Albizia ferruginea",
    "Albizia gummifera",
    "Albizia obbiadensis",
    "Albizia vaughanii",
    "Aloe marlothii",
    "Androstachys",
    "Anogeissus leiocarpa",
    "Anonidium mannii",
    "Antrocaryon micraster",
    "Arbutus canariensis",
    "Aucoumea klaineana",
    "Avicennia germinans",
    "Baikiaea ghesquiereana",
    "Baikiaea insignis",
    "Baillonella",
    "Balanites aegyptiaca",
    "Balanites angolensis",
    "Balanites glabra",
    "Balanites pedicellaris",
    "Balanites rotundifolia",
    "Balanites wilsoniana",
    "Baphia nitida",
    "Bersama abyssinica",
    "Blighia sapida",
    "Bombax buonopozense",
    "Borassus aethiopum",
    "Boscia senegalensis",
    "Boswellia frereana",
    "Brachystegia",
    "Brachystegia angustistipulata",
    "Brachystegia bakeriana",
    "Brachystegia boehmii",
    "Brachystegia eurycoma",
    "Brachystegia glaucescens",
    "Brachystegia kennedyi",
    "Brachystegia laurentii",
    "Brachystegia nigerica",
    "Brachystegia spiciformis",
    "Brachystegia tamarindoides",
    "Brachystegia zenkeri",
    "Bridelia micrantha",
    "Faidherbia",
    "Ficus abutilifolia",
    "Ficus capreifolia",
    "Ficus cordata",
    "Ficus craterostoma",
    "Ficus exasperata",
    "Ficus faulkneriana",
    "Ficus glumosa",
    "Ficus ilicina",
    "Ficus ingens",
    "Ficus lateriflora",
    "Ficus natalensis",
    "Ficus polita",
    "Ficus salicifolia",
    "Ficus sansibarica",
    "Ficus sur",
]

FIRST_NAMES = [
    "Brian",
    "Carlos",
    "Chris",
    "Constanza",
    "Jill",
    "Léann",
    "Peter",
    "Rachel",
    "Steve",
    "Yacin",
    "Yee",
    "Yishan",
]
