CREATE SCHEMA IF NOT EXISTS tracking;

CREATE TABLE tracking.planting_sites (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    organization_id BIGINT NOT NULL REFERENCES organizations ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    boundary GEOMETRY(MULTIPOLYGON, 3857),
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (organization_id, name)
);

CREATE TABLE tracking.planting_zones (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    planting_site_id BIGINT NOT NULL REFERENCES tracking.planting_sites ON DELETE CASCADE,
    name TEXT NOT NULL,
    boundary GEOMETRY(MULTIPOLYGON, 3857),
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (planting_site_id, name)
);

CREATE TABLE tracking.plots (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    planting_zone_id BIGINT NOT NULL REFERENCES tracking.planting_zones ON DELETE CASCADE,
    name TEXT NOT NULL,
    full_name TEXT NOT NULL,
    boundary GEOMETRY(MULTIPOLYGON, 3857),
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (planting_zone_id, name)
);
