-- Replace all blank (all-space or zero-length) values of nullable text columns with nulls and add
-- check constraints to guarantee that we don't store blank values in the future.
--
-- Statements are generated by scanning for all nullable text columns:
--
-- SELECT 'UPDATE ' || table_schema || '.' || table_name
--            || ' SET "' || column_name || '" = NULL'
--            || ' WHERE "' || column_name || '" SIMILAR TO '' *'';'
-- FROM information_schema.columns isc
-- WHERE is_nullable = 'YES'
--   AND data_type = 'text'
--   AND table_schema <> 'pg_catalog'
--   AND NOT EXISTS (
--         SELECT 1
--         FROM information_schema.views isv
--         WHERE isv.table_schema = isc.table_schema
--           AND isv.table_name = isc.table_name)
-- ORDER BY table_schema, table_name, column_name;
--
-- SELECT 'ALTER TABLE ' || table_schema || '.' || table_name
--            || ' ADD CHECK ("' || column_name || '" NOT SIMILAR TO '' *'');'
-- FROM information_schema.columns isc
-- WHERE is_nullable = 'YES'
--   AND data_type = 'text'
--   AND table_schema <> 'pg_catalog'
--   AND NOT EXISTS (
--         SELECT 1
--         FROM information_schema.views isv
--         WHERE isv.table_schema = isc.table_schema
--           AND isv.table_name = isc.table_name)
-- ORDER BY table_schema, table_name, column_name;

UPDATE nursery.batches SET "notes" = NULL WHERE "notes" SIMILAR TO ' *';
UPDATE nursery.withdrawals SET "notes" = NULL WHERE "notes" SIMILAR TO ' *';
UPDATE public.automations SET "description" = NULL WHERE "description" SIMILAR TO ' *';
UPDATE public.automations SET "timeseries_name" = NULL WHERE "timeseries_name" SIMILAR TO ' *';
UPDATE public.device_templates SET "address" = NULL WHERE "address" SIMILAR TO ' *';
UPDATE public.device_templates SET "description" = NULL WHERE "description" SIMILAR TO ' *';
UPDATE public.device_templates SET "protocol" = NULL WHERE "protocol" SIMILAR TO ' *';
UPDATE public.devices SET "address" = NULL WHERE "address" SIMILAR TO ' *';
UPDATE public.devices SET "protocol" = NULL WHERE "protocol" SIMILAR TO ' *';
UPDATE public.facilities SET "description" = NULL WHERE "description" SIMILAR TO ' *';
UPDATE public.gbif_distributions SET "country_code" = NULL WHERE "country_code" SIMILAR TO ' *';
UPDATE public.gbif_distributions SET "establishment_means" = NULL WHERE "establishment_means" SIMILAR TO ' *';
UPDATE public.gbif_distributions SET "occurrence_status" = NULL WHERE "occurrence_status" SIMILAR TO ' *';
UPDATE public.gbif_distributions SET "threat_status" = NULL WHERE "threat_status" SIMILAR TO ' *';
UPDATE public.gbif_names SET "language" = NULL WHERE "language" SIMILAR TO ' *';
UPDATE public.gbif_taxa SET "canonical_name" = NULL WHERE "canonical_name" SIMILAR TO ' *';
UPDATE public.gbif_taxa SET "class" = NULL WHERE "class" SIMILAR TO ' *';
UPDATE public.gbif_taxa SET "dataset_id" = NULL WHERE "dataset_id" SIMILAR TO ' *';
UPDATE public.gbif_taxa SET "family" = NULL WHERE "family" SIMILAR TO ' *';
UPDATE public.gbif_taxa SET "generic_name" = NULL WHERE "generic_name" SIMILAR TO ' *';
UPDATE public.gbif_taxa SET "genus" = NULL WHERE "genus" SIMILAR TO ' *';
UPDATE public.gbif_taxa SET "infraspecific_epithet" = NULL WHERE "infraspecific_epithet" SIMILAR TO ' *';
UPDATE public.gbif_taxa SET "nomenclatural_status" = NULL WHERE "nomenclatural_status" SIMILAR TO ' *';
UPDATE public.gbif_taxa SET "order" = NULL WHERE "order" SIMILAR TO ' *';
UPDATE public.gbif_taxa SET "phylum" = NULL WHERE "phylum" SIMILAR TO ' *';
UPDATE public.gbif_taxa SET "specific_epithet" = NULL WHERE "specific_epithet" SIMILAR TO ' *';
UPDATE public.gbif_vernacular_names SET "country_code" = NULL WHERE "country_code" SIMILAR TO ' *'; UPDATE public.gbif_vernacular_names SET "language" = NULL WHERE "language" SIMILAR TO ' *';
UPDATE public.organizations SET "country_code" = NULL WHERE "country_code" SIMILAR TO ' *';
UPDATE public.organizations SET "country_subdivision_code" = NULL WHERE "country_subdivision_code" SIMILAR TO ' *';
UPDATE public.organizations SET "description" = NULL WHERE "description" SIMILAR TO ' *';
UPDATE public.species SET "common_name" = NULL WHERE "common_name" SIMILAR TO ' *';
UPDATE public.species SET "family_name" = NULL WHERE "family_name" SIMILAR TO ' *';
UPDATE public.species_problems SET "suggested_value" = NULL WHERE "suggested_value" SIMILAR TO ' *';
UPDATE public.timeseries SET "units" = NULL WHERE "units" SIMILAR TO ' *';
UPDATE public.upload_problems SET "field" = NULL WHERE "field" SIMILAR TO ' *';
UPDATE public.upload_problems SET "message" = NULL WHERE "message" SIMILAR TO ' *';
UPDATE public.upload_problems SET "value" = NULL WHERE "value" SIMILAR TO ' *';
UPDATE public.users SET "auth_id" = NULL WHERE "auth_id" SIMILAR TO ' *';
UPDATE public.users SET "first_name" = NULL WHERE "first_name" SIMILAR TO ' *';
UPDATE public.users SET "last_name" = NULL WHERE "last_name" SIMILAR TO ' *';
UPDATE seedbank.accessions SET "collection_site_city" = NULL WHERE "collection_site_city" SIMILAR TO ' *';
UPDATE seedbank.accessions SET "collection_site_country_code" = NULL WHERE "collection_site_country_code" SIMILAR TO ' *';
UPDATE seedbank.accessions SET "collection_site_country_subdivision" = NULL WHERE "collection_site_country_subdivision" SIMILAR TO ' *';
UPDATE seedbank.accessions SET "collection_site_landowner" = NULL WHERE "collection_site_landowner" SIMILAR TO ' *';
UPDATE seedbank.accessions SET "collection_site_name" = NULL WHERE "collection_site_name" SIMILAR TO ' *';
UPDATE seedbank.accessions SET "collection_site_notes" = NULL WHERE "collection_site_notes" SIMILAR TO ' *';
UPDATE seedbank.accessions SET "founder_id" = NULL WHERE "founder_id" SIMILAR TO ' *';
UPDATE seedbank.accessions SET "number" = NULL WHERE "number" SIMILAR TO ' *';
UPDATE seedbank.accessions SET "processing_notes" = NULL WHERE "processing_notes" SIMILAR TO ' *';
UPDATE seedbank.bags SET "bag_number" = NULL WHERE "bag_number" SIMILAR TO ' *';
UPDATE seedbank.viability_tests SET "notes" = NULL WHERE "notes" SIMILAR TO ' *';
UPDATE seedbank.viability_tests SET "staff_responsible" = NULL WHERE "staff_responsible" SIMILAR TO ' *';
UPDATE seedbank.withdrawals SET "destination" = NULL WHERE "destination" SIMILAR TO ' *';
UPDATE seedbank.withdrawals SET "notes" = NULL WHERE "notes" SIMILAR TO ' *';
UPDATE seedbank.withdrawals SET "staff_responsible" = NULL WHERE "staff_responsible" SIMILAR TO ' *';
UPDATE tracking.planting_sites SET "description" = NULL WHERE "description" SIMILAR TO ' *';
UPDATE tracking.plantings SET "notes" = NULL WHERE "notes" SIMILAR TO ' *';

ALTER TABLE nursery.batches ADD CHECK ("notes" NOT SIMILAR TO ' *');
ALTER TABLE nursery.withdrawals ADD CHECK ("notes" NOT SIMILAR TO ' *');
ALTER TABLE public.automations ADD CHECK ("description" NOT SIMILAR TO ' *');
ALTER TABLE public.automations ADD CHECK ("timeseries_name" NOT SIMILAR TO ' *');
ALTER TABLE public.device_templates ADD CHECK ("address" NOT SIMILAR TO ' *');
ALTER TABLE public.device_templates ADD CHECK ("description" NOT SIMILAR TO ' *');
ALTER TABLE public.device_templates ADD CHECK ("protocol" NOT SIMILAR TO ' *');
ALTER TABLE public.devices ADD CHECK ("address" NOT SIMILAR TO ' *');
ALTER TABLE public.devices ADD CHECK ("protocol" NOT SIMILAR TO ' *');
ALTER TABLE public.facilities ADD CHECK ("description" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_distributions ADD CHECK ("country_code" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_distributions ADD CHECK ("establishment_means" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_distributions ADD CHECK ("occurrence_status" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_distributions ADD CHECK ("threat_status" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_names ADD CHECK ("language" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_taxa ADD CHECK ("canonical_name" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_taxa ADD CHECK ("class" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_taxa ADD CHECK ("dataset_id" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_taxa ADD CHECK ("family" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_taxa ADD CHECK ("generic_name" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_taxa ADD CHECK ("genus" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_taxa ADD CHECK ("infraspecific_epithet" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_taxa ADD CHECK ("nomenclatural_status" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_taxa ADD CHECK ("order" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_taxa ADD CHECK ("phylum" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_taxa ADD CHECK ("specific_epithet" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_vernacular_names ADD CHECK ("country_code" NOT SIMILAR TO ' *');
ALTER TABLE public.gbif_vernacular_names ADD CHECK ("language" NOT SIMILAR TO ' *');
ALTER TABLE public.organizations ADD CHECK ("country_code" NOT SIMILAR TO ' *');
ALTER TABLE public.organizations ADD CHECK ("country_subdivision_code" NOT SIMILAR TO ' *');
ALTER TABLE public.organizations ADD CHECK ("description" NOT SIMILAR TO ' *');
ALTER TABLE public.species ADD CHECK ("common_name" NOT SIMILAR TO ' *');
ALTER TABLE public.species ADD CHECK ("family_name" NOT SIMILAR TO ' *');
ALTER TABLE public.species_problems ADD CHECK ("suggested_value" NOT SIMILAR TO ' *');
ALTER TABLE public.timeseries ADD CHECK ("units" NOT SIMILAR TO ' *');
ALTER TABLE public.upload_problems ADD CHECK ("field" NOT SIMILAR TO ' *');
ALTER TABLE public.upload_problems ADD CHECK ("message" NOT SIMILAR TO ' *');
ALTER TABLE public.upload_problems ADD CHECK ("value" NOT SIMILAR TO ' *');
ALTER TABLE public.users ADD CHECK ("auth_id" NOT SIMILAR TO ' *');
ALTER TABLE public.users ADD CHECK ("first_name" NOT SIMILAR TO ' *');
ALTER TABLE public.users ADD CHECK ("last_name" NOT SIMILAR TO ' *');
ALTER TABLE seedbank.accessions ADD CHECK ("collection_site_city" NOT SIMILAR TO ' *');
ALTER TABLE seedbank.accessions ADD CHECK ("collection_site_country_code" NOT SIMILAR TO ' *');
ALTER TABLE seedbank.accessions ADD CHECK ("collection_site_country_subdivision" NOT SIMILAR TO ' *');
ALTER TABLE seedbank.accessions ADD CHECK ("collection_site_landowner" NOT SIMILAR TO ' *');
ALTER TABLE seedbank.accessions ADD CHECK ("collection_site_name" NOT SIMILAR TO ' *');
ALTER TABLE seedbank.accessions ADD CHECK ("collection_site_notes" NOT SIMILAR TO ' *');
ALTER TABLE seedbank.accessions ADD CHECK ("founder_id" NOT SIMILAR TO ' *');
ALTER TABLE seedbank.accessions ADD CHECK ("number" NOT SIMILAR TO ' *');
ALTER TABLE seedbank.accessions ADD CHECK ("processing_notes" NOT SIMILAR TO ' *');
ALTER TABLE seedbank.bags ADD CHECK ("bag_number" NOT SIMILAR TO ' *');
ALTER TABLE seedbank.viability_tests ADD CHECK ("notes" NOT SIMILAR TO ' *');
ALTER TABLE seedbank.viability_tests ADD CHECK ("staff_responsible" NOT SIMILAR TO ' *');
ALTER TABLE seedbank.withdrawals ADD CHECK ("destination" NOT SIMILAR TO ' *');
ALTER TABLE seedbank.withdrawals ADD CHECK ("notes" NOT SIMILAR TO ' *');
ALTER TABLE seedbank.withdrawals ADD CHECK ("staff_responsible" NOT SIMILAR TO ' *');
ALTER TABLE tracking.planting_sites ADD CHECK ("description" NOT SIMILAR TO ' *');
ALTER TABLE tracking.plantings ADD CHECK ("notes" NOT SIMILAR TO ' *');
