CREATE TABLE report_statuses (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE reports (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    organization_id BIGINT NOT NULL REFERENCES organizations,
    year INTEGER NOT NULL,
    quarter INTEGER NOT NULL,
    locked_by BIGINT REFERENCES users,
    locked_time TIMESTAMP WITH TIME ZONE,
    modified_by BIGINT REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE,
    submitted_by BIGINT REFERENCES users,
    submitted_time TIMESTAMP WITH TIME ZONE,
    status_id INTEGER NOT NULL REFERENCES report_statuses,
    body JSONB NOT NULL,

    -- User IDs must be set along with timestamps.
    CONSTRAINT locked_by_and_time_both_set
        CHECK (locked_by IS NULL AND locked_time IS NULL
            OR locked_by IS NOT NULL AND locked_time IS NOT NULL),
    CONSTRAINT submitted_by_and_time_both_set
        CHECK (submitted_by IS NULL AND submitted_time IS NULL
            OR submitted_by IS NOT NULL AND submitted_time IS NOT NULL),

    -- A submitted report can't be locked, and a report can't remain locked after it's submitted.
    CONSTRAINT cannot_submit_while_locked CHECK (locked_time IS NULL OR submitted_time IS NULL),

    -- Status is locked (3) iff lock is held by someone.
    CONSTRAINT status_reflects_locked
        CHECK (locked_by IS NULL AND status_id <> 3
            OR locked_by IS NOT NULL AND status_id = 3),

    -- BETWEEN is inclusive
    CONSTRAINT quarter_in_range CHECK (quarter BETWEEN 1 and 4),

    CONSTRAINT one_report_per_quarter UNIQUE (organization_id, year, quarter)
);

CREATE TABLE report_photos (
    report_id BIGINT NOT NULL REFERENCES reports,
    photo_id BIGINT NOT NULL REFERENCES photos ON DELETE CASCADE,
    caption TEXT,

    PRIMARY KEY (report_id, photo_id),
    CONSTRAINT photo_not_shared_between_reports UNIQUE (photo_id)
);
