INSERT INTO countries (code, name, region_id)
VALUES ('AD', 'Andorra', 3),
       ('AE', 'United Arab Emirates', 5),
       ('AF', 'Afghanistan', 8),
       ('AG', 'Antigua and Barbuda', 4),
       ('AI', 'Anguilla', 4),
       ('AL', 'Albania', 3),
       ('AM', 'Armenia', 3),
       ('AO', 'Angola', 9),
       ('AQ', 'Antarctica', 1),
       ('AR', 'Argentina', 4),
       ('AS', 'American Samoa', 7),
       ('AT', 'Austria', 3),
       ('AU', 'Australia', 7),
       ('AW', 'Aruba', 4),
       ('AX', 'Åland Islands', 3),
       ('AZ', 'Azerbaijan', 3),
       ('BA', 'Bosnia and Herzegovina', 3),
       ('BB', 'Barbados', 4),
       ('BD', 'Bangladesh', 8),
       ('BE', 'Belgium', 3),
       ('BF', 'Burkina Faso', 9),
       ('BG', 'Bulgaria', 3),
       ('BH', 'Bahrain', 5),
       ('BI', 'Burundi', 9),
       ('BJ', 'Benin', 9),
       ('BL', 'St. Barthélemy', 4),
       ('BM', 'Bermuda', 6),
       ('BN', 'Brunei', 2),
       ('BO', 'Bolivia', 4),
       ('BQ', 'Caribbean Netherlands', 4),
       ('BR', 'Brazil', 4),
       ('BS', 'Bahamas', 4),
       ('BT', 'Bhutan', 8),
       ('BV', 'Bouvet Island', 1),
       ('BW', 'Botswana', 9),
       ('BY', 'Belarus', 3),
       ('BZ', 'Belize', 4),
       ('CA', 'Canada', 6),
       ('CC', 'Cocos (Keeling) Islands', 7),
       ('CD', 'Congo - Kinshasa', 9),
       ('CF', 'Central African Republic', 9),
       ('CG', 'Congo - Brazzaville', 9),
       ('CH', 'Switzerland', 3),
       ('CI', 'Côte d’Ivoire', 9),
       ('CK', 'Cook Islands', 7),
       ('CL', 'Chile', 4),
       ('CM', 'Cameroon', 9),
       ('CN', 'China', 2),
       ('CO', 'Colombia', 4),
       ('CR', 'Costa Rica', 4),
       ('CU', 'Cuba', 4),
       ('CV', 'Cape Verde', 9),
       ('CW', 'Curaçao', 4),
       ('CX', 'Christmas Island', 7),
       ('CY', 'Cyprus', 3),
       ('CZ', 'Czech Republic', 3),
       ('DE', 'Germany', 3),
       ('DJ', 'Djibouti', 9),
       ('DK', 'Denmark', 3),
       ('DM', 'Dominica', 4),
       ('DO', 'Dominican Republic', 4),
       ('DZ', 'Algeria', 5),
       ('EC', 'Ecuador', 4),
       ('EE', 'Estonia', 3),
       ('EG', 'Egypt', 5),
       ('EH', 'Western Sahara', 5),
       ('ER', 'Eritrea', 9),
       ('ES', 'Spain', 3),
       ('ET', 'Ethiopia', 9),
       ('FI', 'Finland', 3),
       ('FJ', 'Fiji', 7),
       ('FK', 'Falkland Islands', 4),
       ('FM', 'Micronesia', 7),
       ('FO', 'Faroe Islands', 3),
       ('FR', 'France', 3),
       ('GA', 'Gabon', 9),
       ('GB', 'United Kingdom', 3),
       ('GD', 'Grenada', 4),
       ('GE', 'Georgia', 3),
       ('GF', 'French Guiana', 4),
       ('GG', 'Guernsey', 3),
       ('GH', 'Ghana', 9),
       ('GI', 'Gibraltar', 3),
       ('GL', 'Greenland', 6),
       ('GM', 'Gambia', 9),
       ('GN', 'Guinea', 9),
       ('GP', 'Guadeloupe', 4),
       ('GQ', 'Equatorial Guinea', 9),
       ('GR', 'Greece', 3),
       ('GS', 'South Georgia & South Sandwich Islands', 1),
       ('GT', 'Guatemala', 4),
       ('GU', 'Guam', 7),
       ('GW', 'Guinea-Bissau', 9),
       ('GY', 'Guyana', 4),
       ('HK', 'Hong Kong SAR China', 2),
       ('HM', 'Heard & McDonald Islands', 1),
       ('HN', 'Honduras', 4),
       ('HR', 'Croatia', 3),
       ('HT', 'Haiti', 4),
       ('HU', 'Hungary', 3),
       ('ID', 'Indonesia', 2),
       ('IE', 'Ireland', 3),
       ('IL', 'Israel', 5),
       ('IM', 'Isle of Man', 3),
       ('IN', 'India', 8),
       ('IO', 'British Indian Ocean Territory', 8),
       ('IQ', 'Iraq', 5),
       ('IR', 'Iran', 5),
       ('IS', 'Iceland', 3),
       ('IT', 'Italy', 3),
       ('JE', 'Jersey', 3),
       ('JM', 'Jamaica', 4),
       ('JO', 'Jordan', 5),
       ('JP', 'Japan', 2),
       ('KE', 'Kenya', 9),
       ('KG', 'Kyrgyzstan', 3),
       ('KH', 'Cambodia', 2),
       ('KI', 'Kiribati', 7),
       ('KM', 'Comoros', 9),
       ('KN', 'Saint Kitts and Nevis', 4),
       ('KP', 'North Korea', 2),
       ('KR', 'South Korea', 2),
       ('KW', 'Kuwait', 5),
       ('KY', 'Cayman Islands', 4),
       ('KZ', 'Kazakhstan', 3),
       ('LA', 'Laos', 2),
       ('LB', 'Lebanon', 5),
       ('LC', 'Saint Lucia', 4),
       ('LI', 'Liechtenstein', 3),
       ('LK', 'Sri Lanka', 8),
       ('LR', 'Liberia', 9),
       ('LS', 'Lesotho', 9),
       ('LT', 'Lithuania', 3),
       ('LU', 'Luxembourg', 3),
       ('LV', 'Latvia', 3),
       ('LY', 'Libya', 5),
       ('MA', 'Morocco', 5),
       ('MC', 'Monaco', 3),
       ('MD', 'Moldova', 3),
       ('ME', 'Montenegro', 3),
       ('MF', 'St. Martin', 4),
       ('MG', 'Madagascar', 9),
       ('MH', 'Marshall Islands', 7),
       ('MK', 'North Macedonia', 3),
       ('ML', 'Mali', 9),
       ('MM', 'Myanmar', 2),
       ('MN', 'Mongolia', 2),
       ('MO', 'Macao SAR China', 2),
       ('MP', 'Northern Mariana Islands', 7),
       ('MQ', 'Martinique', 4),
       ('MR', 'Mauritania', 9),
       ('MS', 'Montserrat', 4),
       ('MT', 'Malta', 3),
       ('MU', 'Mauritius', 9),
       ('MV', 'Maldives', 8),
       ('MW', 'Malawi', 9),
       ('MX', 'Mexico', 4),
       ('MY', 'Malaysia', 2),
       ('MZ', 'Mozambique', 9),
       ('NA', 'Namibia', 9),
       ('NC', 'New Caledonia', 7),
       ('NE', 'Niger', 9),
       ('NF', 'Norfolk Island', 7),
       ('NG', 'Nigeria', 9),
       ('NI', 'Nicaragua', 4),
       ('NL', 'Netherlands', 3),
       ('NO', 'Norway', 3),
       ('NP', 'Nepal', 8),
       ('NR', 'Nauru', 7),
       ('NU', 'Niue', 7),
       ('NZ', 'New Zealand', 7),
       ('OM', 'Oman', 5),
       ('PA', 'Panama', 4),
       ('PE', 'Peru', 4),
       ('PF', 'French Polynesia', 7),
       ('PG', 'Papua New Guinea', 7),
       ('PH', 'Philippines', 2),
       ('PK', 'Pakistan', 8),
       ('PL', 'Poland', 3),
       ('PM', 'St. Pierre & Miquelon', 6),
       ('PN', 'Pitcairn Islands', 7),
       ('PR', 'Puerto Rico', 4),
       ('PS', 'Palestinian Territories', 5),
       ('PT', 'Portugal', 3),
       ('PW', 'Palau', 7),
       ('PY', 'Paraguay', 4),
       ('QA', 'Qatar', 5),
       ('RE', 'Réunion', 9),
       ('RO', 'Romania', 3),
       ('RS', 'Serbia', 3),
       ('RU', 'Russia', 3),
       ('RW', 'Rwanda', 9),
       ('SA', 'Saudi Arabia', 5),
       ('SB', 'Solomon Islands', 7),
       ('SC', 'Seychelles', 9),
       ('SD', 'Sudan', 9),
       ('SE', 'Sweden', 3),
       ('SG', 'Singapore', 2),
       ('SH', 'St. Helena', 9),
       ('SI', 'Slovenia', 3),
       ('SJ', 'Svalbard & Jan Mayen', 3),
       ('SK', 'Slovakia', 3),
       ('SL', 'Sierra Leone', 9),
       ('SM', 'San Marino', 3),
       ('SN', 'Senegal', 9),
       ('SO', 'Somalia', 9),
       ('SR', 'Suriname', 4),
       ('SS', 'South Sudan', 9),
       ('ST', 'Sao Tome and Principe', 9),
       ('SV', 'El Salvador', 4),
       ('SX', 'Sint Maarten', 4),
       ('SY', 'Syria', 5),
       ('SZ', 'Eswatini', 9),
       ('TC', 'Turks & Caicos Islands', 4),
       ('TD', 'Chad', 9),
       ('TF', 'French Southern Territories', 1),
       ('TG', 'Togo', 9),
       ('TH', 'Thailand', 2),
       ('TJ', 'Tajikistan', 3),
       ('TK', 'Tokelau', 7),
       ('TL', 'East Timor', 2),
       ('TM', 'Turkmenistan', 3),
       ('TN', 'Tunisia', 5),
       ('TO', 'Tonga', 7),
       ('TR', 'Turkey', 3),
       ('TT', 'Trinidad and Tobago', 4),
       ('TV', 'Tuvalu', 7),
       ('TW', 'Taiwan', 2),
       ('TZ', 'Tanzania', 9),
       ('UA', 'Ukraine', 3),
       ('UG', 'Uganda', 9),
       ('UM', 'U.S. Outlying Islands', 7),
       ('US', 'United States', 6),
       ('UY', 'Uruguay', 4),
       ('UZ', 'Uzbekistan', 3),
       ('VA', 'Vatican City (Holy See)', 3),
       ('VC', 'Saint Vincent and the Grenadines', 4),
       ('VE', 'Venezuela', 4),
       ('VG', 'British Virgin Islands', 4),
       ('VI', 'U.S. Virgin Islands', 4),
       ('VN', 'Vietnam', 2),
       ('VU', 'Vanuatu', 7),
       ('WF', 'Wallis & Futuna', 7),
       ('WS', 'Samoa', 7),
       ('YE', 'Yemen', 5),
       ('YT', 'Mayotte', 9),
       ('ZA', 'South Africa', 9),
       ('ZM', 'Zambia', 9),
       ('ZW', 'Zimbabwe', 9)
ON CONFLICT (code) DO UPDATE
SET name = excluded.name,
    region_id = excluded.region_id;

INSERT INTO country_subdivisions (code, country_code, name)
VALUES ('US-AL', 'US', 'Alabama'),
       ('US-AK', 'US', 'Alaska'),
       ('US-AR', 'US', 'Arkansas'),
       ('US-AS', 'US', 'American Samoa'),
       ('US-AZ', 'US', 'Arizona'),
       ('US-CA', 'US', 'California'),
       ('US-CO', 'US', 'Colorado'),
       ('US-CT', 'US', 'Connecticut'),
       ('US-DC', 'US', 'District of Columbia'),
       ('US-DE', 'US', 'Delaware'),
       ('US-FL', 'US', 'Florida'),
       ('US-GA', 'US', 'Georgia'),
       ('US-GU', 'US', 'Guam'),
       ('US-HI', 'US', 'Hawaii'),
       ('US-IA', 'US', 'Iowa'),
       ('US-ID', 'US', 'Idaho'),
       ('US-IL', 'US', 'Illinois'),
       ('US-IN', 'US', 'Indiana'),
       ('US-KS', 'US', 'Kansas'),
       ('US-KY', 'US', 'Kentucky'),
       ('US-LA', 'US', 'Louisiana'),
       ('US-MA', 'US', 'Massachusetts'),
       ('US-MD', 'US', 'Maryland'),
       ('US-ME', 'US', 'Maine'),
       ('US-MI', 'US', 'Michigan'),
       ('US-MN', 'US', 'Minnesota'),
       ('US-MO', 'US', 'Missouri'),
       ('US-MP', 'US', 'Northern Mariana Islands'),
       ('US-MS', 'US', 'Mississippi'),
       ('US-MT', 'US', 'Montana'),
       ('US-NC', 'US', 'North Carolina'),
       ('US-ND', 'US', 'North Dakota'),
       ('US-NE', 'US', 'Nebraska'),
       ('US-NH', 'US', 'New Hampshire'),
       ('US-NJ', 'US', 'New Jersey'),
       ('US-NM', 'US', 'New Mexico'),
       ('US-NV', 'US', 'Nevada'),
       ('US-NY', 'US', 'New York'),
       ('US-OH', 'US', 'Ohio'),
       ('US-OK', 'US', 'Oklahoma'),
       ('US-OR', 'US', 'Oregon'),
       ('US-PA', 'US', 'Pennsylvania'),
       ('US-PR', 'US', 'Puerto Rico'),
       ('US-RI', 'US', 'Rhode Island'),
       ('US-SC', 'US', 'South Carolina'),
       ('US-SD', 'US', 'South Dakota'),
       ('US-TN', 'US', 'Tennessee'),
       ('US-TX', 'US', 'Texas'),
       ('US-UM', 'US', 'U.S. Minor Outlying Islands'),
       ('US-UT', 'US', 'Utah'),
       ('US-VA', 'US', 'Virginia'),
       ('US-VI', 'US', 'U.S. Virgin Islands'),
       ('US-VT', 'US', 'Vermont'),
       ('US-WA', 'US', 'Washington'),
       ('US-WI', 'US', 'Wisconsin'),
       ('US-WV', 'US', 'West Virginia'),
       ('US-WY', 'US', 'Wyoming')
ON CONFLICT (code) DO UPDATE SET name = excluded.name;
