INSERT INTO countries (code, name)
VALUES ('AD', 'Andorra'),
       ('AE', 'United Arab Emirates'),
       ('AF', 'Afghanistan'),
       ('AG', 'Antigua & Barbuda'),
       ('AI', 'Anguilla'),
       ('AL', 'Albania'),
       ('AM', 'Armenia'),
       ('AO', 'Angola'),
       ('AQ', 'Antarctica'),
       ('AR', 'Argentina'),
       ('AS', 'American Samoa'),
       ('AT', 'Austria'),
       ('AU', 'Australia'),
       ('AW', 'Aruba'),
       ('AX', 'Åland Islands'),
       ('AZ', 'Azerbaijan'),
       ('BA', 'Bosnia & Herzegovina'),
       ('BB', 'Barbados'),
       ('BD', 'Bangladesh'),
       ('BE', 'Belgium'),
       ('BF', 'Burkina Faso'),
       ('BG', 'Bulgaria'),
       ('BH', 'Bahrain'),
       ('BI', 'Burundi'),
       ('BJ', 'Benin'),
       ('BL', 'St. Barthélemy'),
       ('BM', 'Bermuda'),
       ('BN', 'Brunei'),
       ('BO', 'Bolivia'),
       ('BQ', 'Caribbean Netherlands'),
       ('BR', 'Brazil'),
       ('BS', 'Bahamas'),
       ('BT', 'Bhutan'),
       ('BV', 'Bouvet Island'),
       ('BW', 'Botswana'),
       ('BY', 'Belarus'),
       ('BZ', 'Belize'),
       ('CA', 'Canada'),
       ('CC', 'Cocos (Keeling) Islands'),
       ('CD', 'Congo - Kinshasa'),
       ('CF', 'Central African Republic'),
       ('CG', 'Congo - Brazzaville'),
       ('CH', 'Switzerland'),
       ('CI', 'Côte d’Ivoire'),
       ('CK', 'Cook Islands'),
       ('CL', 'Chile'),
       ('CM', 'Cameroon'),
       ('CN', 'China'),
       ('CO', 'Colombia'),
       ('CR', 'Costa Rica'),
       ('CU', 'Cuba'),
       ('CV', 'Cape Verde'),
       ('CW', 'Curaçao'),
       ('CX', 'Christmas Island'),
       ('CY', 'Cyprus'),
       ('CZ', 'Czechia'),
       ('DE', 'Germany'),
       ('DJ', 'Djibouti'),
       ('DK', 'Denmark'),
       ('DM', 'Dominica'),
       ('DO', 'Dominican Republic'),
       ('DZ', 'Algeria'),
       ('EC', 'Ecuador'),
       ('EE', 'Estonia'),
       ('EG', 'Egypt'),
       ('EH', 'Western Sahara'),
       ('ER', 'Eritrea'),
       ('ES', 'Spain'),
       ('ET', 'Ethiopia'),
       ('FI', 'Finland'),
       ('FJ', 'Fiji'),
       ('FK', 'Falkland Islands'),
       ('FM', 'Micronesia'),
       ('FO', 'Faroe Islands'),
       ('FR', 'France'),
       ('GA', 'Gabon'),
       ('GB', 'United Kingdom'),
       ('GD', 'Grenada'),
       ('GE', 'Georgia'),
       ('GF', 'French Guiana'),
       ('GG', 'Guernsey'),
       ('GH', 'Ghana'),
       ('GI', 'Gibraltar'),
       ('GL', 'Greenland'),
       ('GM', 'Gambia'),
       ('GN', 'Guinea'),
       ('GP', 'Guadeloupe'),
       ('GQ', 'Equatorial Guinea'),
       ('GR', 'Greece'),
       ('GS', 'South Georgia & South Sandwich Islands'),
       ('GT', 'Guatemala'),
       ('GU', 'Guam'),
       ('GW', 'Guinea-Bissau'),
       ('GY', 'Guyana'),
       ('HK', 'Hong Kong SAR China'),
       ('HM', 'Heard & McDonald Islands'),
       ('HN', 'Honduras'),
       ('HR', 'Croatia'),
       ('HT', 'Haiti'),
       ('HU', 'Hungary'),
       ('ID', 'Indonesia'),
       ('IE', 'Ireland'),
       ('IL', 'Israel'),
       ('IM', 'Isle of Man'),
       ('IN', 'India'),
       ('IO', 'British Indian Ocean Territory'),
       ('IQ', 'Iraq'),
       ('IR', 'Iran'),
       ('IS', 'Iceland'),
       ('IT', 'Italy'),
       ('JE', 'Jersey'),
       ('JM', 'Jamaica'),
       ('JO', 'Jordan'),
       ('JP', 'Japan'),
       ('KE', 'Kenya'),
       ('KG', 'Kyrgyzstan'),
       ('KH', 'Cambodia'),
       ('KI', 'Kiribati'),
       ('KM', 'Comoros'),
       ('KN', 'St. Kitts & Nevis'),
       ('KP', 'North Korea'),
       ('KR', 'South Korea'),
       ('KW', 'Kuwait'),
       ('KY', 'Cayman Islands'),
       ('KZ', 'Kazakhstan'),
       ('LA', 'Laos'),
       ('LB', 'Lebanon'),
       ('LC', 'St. Lucia'),
       ('LI', 'Liechtenstein'),
       ('LK', 'Sri Lanka'),
       ('LR', 'Liberia'),
       ('LS', 'Lesotho'),
       ('LT', 'Lithuania'),
       ('LU', 'Luxembourg'),
       ('LV', 'Latvia'),
       ('LY', 'Libya'),
       ('MA', 'Morocco'),
       ('MC', 'Monaco'),
       ('MD', 'Moldova'),
       ('ME', 'Montenegro'),
       ('MF', 'St. Martin'),
       ('MG', 'Madagascar'),
       ('MH', 'Marshall Islands'),
       ('MK', 'North Macedonia'),
       ('ML', 'Mali'),
       ('MM', 'Myanmar (Burma)'),
       ('MN', 'Mongolia'),
       ('MO', 'Macao SAR China'),
       ('MP', 'Northern Mariana Islands'),
       ('MQ', 'Martinique'),
       ('MR', 'Mauritania'),
       ('MS', 'Montserrat'),
       ('MT', 'Malta'),
       ('MU', 'Mauritius'),
       ('MV', 'Maldives'),
       ('MW', 'Malawi'),
       ('MX', 'Mexico'),
       ('MY', 'Malaysia'),
       ('MZ', 'Mozambique'),
       ('NA', 'Namibia'),
       ('NC', 'New Caledonia'),
       ('NE', 'Niger'),
       ('NF', 'Norfolk Island'),
       ('NG', 'Nigeria'),
       ('NI', 'Nicaragua'),
       ('NL', 'Netherlands'),
       ('NO', 'Norway'),
       ('NP', 'Nepal'),
       ('NR', 'Nauru'),
       ('NU', 'Niue'),
       ('NZ', 'New Zealand'),
       ('OM', 'Oman'),
       ('PA', 'Panama'),
       ('PE', 'Peru'),
       ('PF', 'French Polynesia'),
       ('PG', 'Papua New Guinea'),
       ('PH', 'Philippines'),
       ('PK', 'Pakistan'),
       ('PL', 'Poland'),
       ('PM', 'St. Pierre & Miquelon'),
       ('PN', 'Pitcairn Islands'),
       ('PR', 'Puerto Rico'),
       ('PS', 'Palestinian Territories'),
       ('PT', 'Portugal'),
       ('PW', 'Palau'),
       ('PY', 'Paraguay'),
       ('QA', 'Qatar'),
       ('RE', 'Réunion'),
       ('RO', 'Romania'),
       ('RS', 'Serbia'),
       ('RU', 'Russia'),
       ('RW', 'Rwanda'),
       ('SA', 'Saudi Arabia'),
       ('SB', 'Solomon Islands'),
       ('SC', 'Seychelles'),
       ('SD', 'Sudan'),
       ('SE', 'Sweden'),
       ('SG', 'Singapore'),
       ('SH', 'St. Helena'),
       ('SI', 'Slovenia'),
       ('SJ', 'Svalbard & Jan Mayen'),
       ('SK', 'Slovakia'),
       ('SL', 'Sierra Leone'),
       ('SM', 'San Marino'),
       ('SN', 'Senegal'),
       ('SO', 'Somalia'),
       ('SR', 'Suriname'),
       ('SS', 'South Sudan'),
       ('ST', 'São Tomé & Príncipe'),
       ('SV', 'El Salvador'),
       ('SX', 'Sint Maarten'),
       ('SY', 'Syria'),
       ('SZ', 'Eswatini'),
       ('TC', 'Turks & Caicos Islands'),
       ('TD', 'Chad'),
       ('TF', 'French Southern Territories'),
       ('TG', 'Togo'),
       ('TH', 'Thailand'),
       ('TJ', 'Tajikistan'),
       ('TK', 'Tokelau'),
       ('TL', 'Timor-Leste'),
       ('TM', 'Turkmenistan'),
       ('TN', 'Tunisia'),
       ('TO', 'Tonga'),
       ('TR', 'Turkey'),
       ('TT', 'Trinidad & Tobago'),
       ('TV', 'Tuvalu'),
       ('TW', 'Taiwan'),
       ('TZ', 'Tanzania'),
       ('UA', 'Ukraine'),
       ('UG', 'Uganda'),
       ('UM', 'U.S. Outlying Islands'),
       ('US', 'United States'),
       ('UY', 'Uruguay'),
       ('UZ', 'Uzbekistan'),
       ('VA', 'Vatican City'),
       ('VC', 'St. Vincent & Grenadines'),
       ('VE', 'Venezuela'),
       ('VG', 'British Virgin Islands'),
       ('VI', 'U.S. Virgin Islands'),
       ('VN', 'Vietnam'),
       ('VU', 'Vanuatu'),
       ('WF', 'Wallis & Futuna'),
       ('WS', 'Samoa'),
       ('YE', 'Yemen'),
       ('YT', 'Mayotte'),
       ('ZA', 'South Africa'),
       ('ZM', 'Zambia'),
       ('ZW', 'Zimbabwe')
ON CONFLICT (code) DO UPDATE SET name = excluded.name;

INSERT INTO country_subdivisions (code, country_code, name)
VALUES ('US-AL', 'US', 'Alabama'),
       ('US-AK', 'US', 'Alaska'),
       ('US-AR', 'US', 'Arkansas'),
       ('US-AS', 'US', 'American Samoa'),
       ('US-AZ', 'US', 'Arizona'),
       ('US-CA', 'US', 'California'),
       ('US-CO', 'US', 'Colorado'),
       ('US-CT', 'US', 'Connecticut'),
       ('US-DC', 'US', 'District of Columbia'),
       ('US-DE', 'US', 'Delaware'),
       ('US-FL', 'US', 'Florida'),
       ('US-GA', 'US', 'Georgia'),
       ('US-GU', 'US', 'Guam'),
       ('US-HI', 'US', 'Hawaii'),
       ('US-IA', 'US', 'Iowa'),
       ('US-ID', 'US', 'Idaho'),
       ('US-IL', 'US', 'Illinois'),
       ('US-IN', 'US', 'Indiana'),
       ('US-KS', 'US', 'Kansas'),
       ('US-KY', 'US', 'Kentucky'),
       ('US-LA', 'US', 'Louisiana'),
       ('US-MA', 'US', 'Massachusetts'),
       ('US-MD', 'US', 'Maryland'),
       ('US-ME', 'US', 'Maine'),
       ('US-MI', 'US', 'Michigan'),
       ('US-MN', 'US', 'Minnesota'),
       ('US-MO', 'US', 'Missouri'),
       ('US-MP', 'US', 'Northern Mariana Islands'),
       ('US-MS', 'US', 'Mississippi'),
       ('US-MT', 'US', 'Montana'),
       ('US-NC', 'US', 'North Carolina'),
       ('US-ND', 'US', 'North Dakota'),
       ('US-NE', 'US', 'Nebraska'),
       ('US-NH', 'US', 'New Hampshire'),
       ('US-NJ', 'US', 'New Jersey'),
       ('US-NM', 'US', 'New Mexico'),
       ('US-NV', 'US', 'Nevada'),
       ('US-NY', 'US', 'New York'),
       ('US-OH', 'US', 'Ohio'),
       ('US-OK', 'US', 'Oklahoma'),
       ('US-OR', 'US', 'Oregon'),
       ('US-PA', 'US', 'Pennsylvania'),
       ('US-PR', 'US', 'Puerto Rico'),
       ('US-RI', 'US', 'Rhode Island'),
       ('US-SC', 'US', 'South Carolina'),
       ('US-SD', 'US', 'South Dakota'),
       ('US-TN', 'US', 'Tennessee'),
       ('US-TX', 'US', 'Texas'),
       ('US-UM', 'US', 'U.S. Minor Outlying Islands'),
       ('US-UT', 'US', 'Utah'),
       ('US-VA', 'US', 'Virginia'),
       ('US-VI', 'US', 'U.S. Virgin Islands'),
       ('US-VT', 'US', 'Vermont'),
       ('US-WA', 'US', 'Washington'),
       ('US-WI', 'US', 'Wisconsin'),
       ('US-WV', 'US', 'West Virginia'),
       ('US-WY', 'US', 'Wyoming')
ON CONFLICT (code) DO UPDATE SET name = excluded.name;
