CREATE SCHEMA IF NOT EXISTS nursery;

CREATE TABLE nursery.batches (
    id                                   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version                              INTEGER NOT NULL,
    organization_id                      BIGINT NOT NULL REFERENCES organizations ON DELETE CASCADE,
    facility_id                          BIGINT NOT NULL REFERENCES facilities ON DELETE CASCADE,
    species_id                           BIGINT NOT NULL REFERENCES species,
    batch_number                         TEXT NOT NULL,
    added_date                           DATE NOT NULL,
    germinating_quantity                 INTEGER NOT NULL,
    not_ready_quantity                   INTEGER NOT NULL,
    ready_quantity                       INTEGER NOT NULL,
    latest_observed_germinating_quantity INTEGER NOT NULL,
    latest_observed_not_ready_quantity   INTEGER NOT NULL,
    latest_observed_ready_quantity       INTEGER NOT NULL,
    latest_observed_time                 TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by                           BIGINT NOT NULL REFERENCES users,
    created_time                         TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_by                          BIGINT NOT NULL REFERENCES users,
    modified_time                        TIMESTAMP WITH TIME ZONE NOT NULL,
    notes                                TEXT,
    ready_by_date                        DATE,
    accession_id                         BIGINT REFERENCES seedbank.accessions,

    UNIQUE (organization_id, batch_number),
    CHECK (germinating_quantity >= 0),
    CHECK (not_ready_quantity >= 0),
    CHECK (ready_quantity >= 0),
    CHECK (latest_observed_germinating_quantity >= 0),
    CHECK (latest_observed_not_ready_quantity >= 0),
    CHECK (latest_observed_ready_quantity >= 0),
    CHECK (version > 0)
);

CREATE INDEX ON nursery.batches (organization_id, species_id);

CREATE TABLE nursery.withdrawal_purposes (
    id   INTEGER PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE nursery.withdrawals (
    id                      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    facility_id             BIGINT NOT NULL REFERENCES facilities ON DELETE CASCADE,
    purpose_id              INTEGER NOT NULL REFERENCES nursery.withdrawal_purposes,
    withdrawn_date          DATE NOT NULL,
    created_by              BIGINT NOT NULL REFERENCES users,
    created_time            TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_by             BIGINT NOT NULL REFERENCES users,
    modified_time           TIMESTAMP WITH TIME ZONE NOT NULL,
    destination             TEXT,
    destination_facility_id BIGINT REFERENCES facilities ON DELETE CASCADE,
    reason                  TEXT,

    -- Purpose ID 1 is Nursery Transfer
    CHECK ((purpose_id = 1 AND destination_facility_id IS NOT NULL) OR
           (purpose_id <> 1 AND destination_facility_id IS NULL))
);

CREATE INDEX ON nursery.withdrawals (destination_facility_id);
CREATE INDEX ON nursery.withdrawals (facility_id);

CREATE TABLE nursery.batch_withdrawals (
    batch_id                       BIGINT NOT NULL REFERENCES nursery.batches ON DELETE CASCADE,
    withdrawal_id                  BIGINT NOT NULL REFERENCES nursery.withdrawals ON DELETE CASCADE,
    germinating_quantity_withdrawn INTEGER NOT NULL,
    not_ready_quantity_withdrawn   INTEGER NOT NULL,
    ready_quantity_withdrawn       INTEGER NOT NULL,
    destination_batch_id           BIGINT REFERENCES nursery.batches ON DELETE CASCADE,

    PRIMARY KEY (batch_id, withdrawal_id),
    CHECK (germinating_quantity_withdrawn >= 0),
    CHECK (not_ready_quantity_withdrawn >= 0),
    CHECK (ready_quantity_withdrawn >= 0)
);

CREATE INDEX ON nursery.batch_withdrawals (withdrawal_id);

CREATE TABLE nursery.batch_quantity_history_types (
    id   INTEGER PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE nursery.batch_quantity_history (
    id                   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    batch_id             BIGINT NOT NULL REFERENCES nursery.batches ON DELETE CASCADE,
    history_type_id      INTEGER NOT NULL REFERENCES nursery.batch_quantity_history_types,
    created_by           BIGINT NOT NULL REFERENCES users,
    created_time         TIMESTAMP WITH TIME ZONE NOT NULL,
    germinating_quantity INTEGER NOT NULL,
    not_ready_quantity   INTEGER NOT NULL,
    ready_quantity       INTEGER NOT NULL,
    withdrawal_id        BIGINT REFERENCES nursery.withdrawals ON DELETE CASCADE,

    CHECK (germinating_quantity >= 0),
    CHECK (not_ready_quantity >= 0),
    CHECK (ready_quantity >= 0)
);

CREATE INDEX ON nursery.batch_quantity_history (batch_id);
