CREATE TABLE conservation_statuses (
    id VARCHAR(2) PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE plant_forms (
    id INTEGER PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

ALTER TABLE species_rare_types RENAME TO rare_types;

ALTER TABLE species_families RENAME TO families;
ALTER SEQUENCE species_family_id_seq RENAME TO family_id_seq;
ALTER TABLE families RENAME COLUMN name TO scientific_name;
ALTER TABLE families ADD COLUMN modified_time TIMESTAMP WITH TIME ZONE;
UPDATE families SET modified_time = created_time WHERE modified_time IS NULL;
ALTER TABLE families ALTER COLUMN modified_time SET NOT NULL;

CREATE TABLE family_names (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    family_id BIGINT NOT NULL REFERENCES families,
    name TEXT NOT NULL,
    locale TEXT,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE species ADD COLUMN family_id BIGINT REFERENCES families;
ALTER TABLE species RENAME COLUMN name TO scientific_name;
ALTER TABLE species ADD COLUMN plant_form_id INTEGER REFERENCES plant_forms;
ALTER TABLE species ADD COLUMN conservation_status_id VARCHAR(2) REFERENCES conservation_statuses;
ALTER TABLE species ADD COLUMN rare_type_id INTEGER REFERENCES rare_types;
ALTER TABLE species ADD COLUMN native_range geometry;
ALTER TABLE species ADD COLUMN tsn TEXT;

CREATE TABLE species_names (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    species_id BIGINT NOT NULL REFERENCES species,
    organization_id BIGINT REFERENCES organizations,
    name TEXT NOT NULL,
    is_scientific BOOLEAN,
    locale TEXT,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE species_options (
   id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   species_id BIGINT NOT NULL REFERENCES species,
   organization_id BIGINT NOT NULL REFERENCES organizations,
   project_id BIGINT REFERENCES projects,
   site_id BIGINT REFERENCES sites,
   created_time TIMESTAMP WITH TIME ZONE NOT NULL,
   modified_time TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE accessions RENAME COLUMN species_rare_type_id TO rare_type_id;
ALTER TABLE accessions RENAME COLUMN species_family_id TO family_id;
