CREATE TABLE upload_statuses (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    finished BOOLEAN NOT NULL
);

CREATE TABLE upload_types (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    expire_files BOOLEAN NOT NULL
);

CREATE TABLE uploads (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    filename TEXT NOT NULL,
    storage_url TEXT NOT NULL,
    content_type TEXT NOT NULL,
    type_id INTEGER NOT NULL REFERENCES upload_types,
    status_id INTEGER NOT NULL REFERENCES upload_statuses,
    organization_id BIGINT REFERENCES organizations
);

CREATE TABLE upload_problem_types (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE upload_problems (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    upload_id BIGINT NOT NULL REFERENCES uploads,
    type_id INTEGER NOT NULL REFERENCES upload_problem_types,
    is_error BOOLEAN NOT NULL,
    position INTEGER,
    field TEXT,
    message TEXT,
    value TEXT
);

CREATE INDEX ON upload_problems (upload_id);
