CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_id TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    first_name TEXT,
    last_name TEXT,
    super_admin BOOLEAN NOT NULL,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE photos ADD COLUMN user_id BIGINT REFERENCES users (id);
ALTER TABLE photos DROP COLUMN account_id;

-- Don't panic! We weren't using this table previously and it is empty.
DROP VIEW active_accounts;
DROP TABLE accounts;

ALTER TABLE organizations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE organizations ADD COLUMN location TEXT;
ALTER TABLE organizations ADD COLUMN created_time TIMESTAMP WITH TIME ZONE;
ALTER TABLE organizations ADD COLUMN modified_time TIMESTAMP WITH TIME ZONE;
ALTER TABLE organizations ADD COLUMN disabled_time TIMESTAMP WITH TIME ZONE;

UPDATE organizations
SET created_time  = NOW(),
    modified_time = NOW(),
    disabled_time = CASE WHEN NOT enabled THEN NOW() END
WHERE created_time IS NULL;

ALTER TABLE organizations ALTER COLUMN created_time SET NOT NULL;
ALTER TABLE organizations ALTER COLUMN modified_time SET NOT NULL;
ALTER TABLE organizations DROP COLUMN enabled;

CREATE TABLE roles (
    id INTEGER PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE organization_users (
    user_id BIGINT NOT NULL REFERENCES users (id),
    organization_id BIGINT NOT NULL REFERENCES organizations (id),
    role_id INTEGER NOT NULL REFERENCES roles (id),
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (user_id, organization_id)
);

ALTER TABLE projects ADD COLUMN pm_user_id BIGINT REFERENCES users (id);

CREATE TABLE project_users (
    user_id BIGINT NOT NULL REFERENCES users (id),
    project_id BIGINT NOT NULL REFERENCES projects (id),
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (user_id, project_id)
);
