CREATE TABLE ecoregions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    object_id TEXT NOT NULL UNIQUE,
    eco_name TEXT NOT NULL,
    biome_number TEXT NOT NULL,
    biome_name TEXT NOT NULL,
    realm TEXT NOT NULL,
    eco_biome_code TEXT NOT NULL,
    eco_id TEXT NOT NULL,
    boundary GEOMETRY NOT NULL
);

CREATE TABLE ecoregion_countries (
    ecoregion_id BIGINT NOT NULL REFERENCES ecoregions (id) ON DELETE CASCADE,
    country_code TEXT NOT NULL REFERENCES countries (code) ON DELETE CASCADE,

    PRIMARY KEY (ecoregion_id, country_code)
);
