CREATE TABLE botanical_countries (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    level3_code TEXT UNIQUE NOT NULL,
    level2_code INTEGER NOT NULL,
    level1_code INTEGER NOT NULL,
    boundary GEOMETRY NOT NULL
);

CREATE TABLE ecoregion_botanical_countries (
    ecoregion_id BIGINT NOT NULL REFERENCES ecoregions ON DELETE CASCADE,
    botanical_country_id BIGINT NOT NULL REFERENCES botanical_countries ON DELETE CASCADE,
    PRIMARY KEY (ecoregion_id, botanical_country_id)
);

CREATE INDEX ON ecoregion_botanical_countries (botanical_country_id);
