CREATE TABLE griis_resources (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    resource_name TEXT NOT NULL UNIQUE,
    country_code TEXT NOT NULL REFERENCES countries (code) ON DELETE CASCADE,
    publication_date DATE NOT NULL,
    updated_time TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX ON griis_resources (country_code);

CREATE TABLE griis_taxa (
    griis_resource_id BIGINT NOT NULL REFERENCES griis_resources ON DELETE CASCADE,
    taxon_id BIGINT NOT NULL,
    scientific_name TEXT NOT NULL,
    accepted_name_usage TEXT,
    taxon_rank TEXT NOT NULL,
    taxonomic_status TEXT NOT NULL,
    occurrence_status TEXT,
    establishment_means TEXT,
    is_invasive BOOLEAN NOT NULL,
    habitat TEXT,

    PRIMARY KEY (griis_resource_id, taxon_id)
);
