CREATE TABLE file_batches
(
  id           BIGINT                   PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_by   BIGINT                   NOT NULL REFERENCES users,
  created_time TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE files ADD COLUMN file_batch_id BIGINT REFERENCES file_batches ON DELETE SET NULL;

CREATE INDEX ON files (file_batch_id);
