CREATE TABLE accelerator.application_statuses (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE accelerator.applications (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_id BIGINT NOT NULL REFERENCES projects ON DELETE CASCADE,
    internal_name TEXT NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,
    application_status_id INTEGER NOT NULL REFERENCES accelerator.application_statuses,
    boundary GEOMETRY,
    internal_comment TEXT,
    feedback TEXT,

    UNIQUE (project_id)
);

CREATE INDEX ON accelerator.applications (created_by);
CREATE INDEX ON accelerator.applications (modified_by);

CREATE TABLE accelerator.application_histories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    application_id BIGINT NOT NULL REFERENCES accelerator.applications ON DELETE CASCADE,
    modified_by BIGINT NOT NULL REFERENCES users,
    modified_time TIMESTAMP WITH TIME ZONE NOT NULL,
    application_status_id INTEGER NOT NULL REFERENCES accelerator.application_statuses,
    boundary GEOMETRY,
    internal_comment TEXT,
    feedback TEXT
);

CREATE INDEX ON accelerator.application_histories (application_id);
CREATE INDEX ON accelerator.application_histories (modified_by);

CREATE TABLE accelerator.application_module_statuses (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE accelerator.application_modules (
    application_id BIGINT NOT NULL REFERENCES accelerator.applications ON DELETE CASCADE,
    module_id BIGINT NOT NULL REFERENCES accelerator.modules,
    application_module_status_id INTEGER NOT NULL REFERENCES accelerator.application_module_statuses
);

CREATE INDEX ON accelerator.application_modules (application_id);
