name: scripts

on:
  pull_request:
    paths:
    - scripts/**
    - .github/workflows/scripts.yml

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"

    - name: Cache dependencies
      id: cache-scripts-python
      uses: actions/cache@v4
      with:
        path: scripts/.venv
        key: 1-${{ hashFiles('scripts/requirements.txt', '.github/workflows/scripts.yml') }}

    - name: Install dependencies
      run: |
        cd scripts
        if [ ! -d .venv ]; then
          python3 -m venv .venv
        fi
        source .venv/bin/activate
        pip3 install -r requirements.txt

    - name: Check format
      run: |
        cd scripts
        source .venv/bin/activate
        black --check .

    - name: Check types
      run: |
        cd scripts
        source .venv/bin/activate
        mypy .
