---
name: setup-java

jobs:
  setup:
    steps:
    - name: Set environment
      run: ./.github/scripts/set-environment.sh

    - name: Set up Java
      id: setup-java
      uses: actions/setup-java@v3
      with:
        distribution: "corretto"
        java-version: "20"

    - name: Tell Gradle where the Java installation is
      run: |
        echo "org.gradle.java.installations.paths=${{ steps.setup-java.outputs.path }}" >> gradle.properties

    - name: Cache dependencies
      id: cache-gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle
          ~/.m2
          node_modules
        # Use the same cache key as in main.yml to pick up cached dependencies
        key: 4-${{ hashFiles('*.gradle.kts', 'gradle.properties', 'yarn.lock') }}

    - name: Download PostGIS image
      run: |
        docker pull postgis/postgis:13-3.0
